Fixed broken links
WeMakeDevs/wemakedevs pull request #111
Opened 2022-11-06 14:20 UTC by enricopro

Different buttons in the website took to the dead pages.

## Fixes Issue

This PR fixes the following issues:

closes #109

## Changes proposed

Here comes all the changes proposed through this PR

I modified the code changing the dead <a> tag with <Link> tag when possible. I test them and they work.

## Check List

- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

2022-11-06 15:51 UTC, AnuragThePathak requested changes

2022-11-06 15:51 UTC, AnuragThePathak commented on src/components/Footer.js
> +  	 				<li><Link to="/">About</Link></li>
I would recommend adding link to the exact section too.

2022-11-06 15:51 UTC, AnuragThePathak commented on src/components/Header.js
> +                <a href="https://www.youtube.com/playlist?list=PL9gnSGHSqcnqwmKYZ5rHuzqe32Di47KMr"><button className="header_button"> Check out our most recent podcast
Do we not have any podcast section or page? In case we have it would be better to link there only.

2022-11-07 17:05 UTC, enricopro commented on src/components/Footer.js
> +  	 				<li><Link to="/">About</Link></li>
With this fix they take you to the dedicate page of that topic. For example, if you click "Events" in the footer, it will take you to https://commclassroom.org/event. Is this what you would like to have?

2022-11-07 17:08 UTC, enricopro commented on src/components/Header.js
> +                <a href="https://www.youtube.com/playlist?list=PL9gnSGHSqcnqwmKYZ5rHuzqe32Di47KMr"><button className="header_button"> Check out our most recent podcast
Done! Now it takes you to the "Podcast" subsection and then you can reach Youtube clicking "See all episodes" button.

2022-11-08 05:31 UTC, AnuragThePathak requested changes

2022-11-08 05:31 UTC, AnuragThePathak commented on src/components/Navbar.js
> +        <li className='navbar-item'><a href="/#podcast">Podcasts</a></li>
This change is undesired.

2022-11-08 05:31 UTC, AnuragThePathak commented on src/components/Header.js
> +                <a href="https://www.youtube.com/playlist?list=PL9gnSGHSqcnqwmKYZ5rHuzqe32Di47KMr"><button className="header_button"> Check out our most recent podcast
change it to /#podcast

2022-11-08 08:49 UTC, enricopro commented on src/components/Navbar.js
> +        <li className='navbar-item'><a href="/#podcast">Podcasts</a></li>
Okay, sorry. Fixed.

2022-11-08 08:50 UTC, enricopro commented on src/components/Header.js
> +                <a href="https://www.youtube.com/playlist?list=PL9gnSGHSqcnqwmKYZ5rHuzqe32Di47KMr"><button className="header_button"> Check out our most recent podcast
Done.

2022-11-08 10:24 UTC, AnuragThePathak requested changes

2022-11-08 10:24 UTC, AnuragThePathak commented on src/components/Footer.js
> +  	 				<li><a href="/#about">About</a></li>
This should be changed to Link

2022-11-08 10:24 UTC, AnuragThePathak commented on src/components/Header.js
> +                <a href="/#podcast"><button className="header_button"> Check out our most recent podcast
Change it to Link too.

2022-11-08 15:40 UTC, enricopro commented on src/components/Footer.js
> +  	 				<li><Link to="/">About</Link></li>
> With this fix they take you to the dedicate page of that topic. For example, if you click "Events" in the footer, it will take you to https://commclassroom.org/event. Is this what you would like to have?

@AnuragThePathak ?

2022-11-08 15:44 UTC, AnuragThePathak commented on src/components/Footer.js
> +  	 				<li><Link to="/">About</Link></li>
What fix didn't get you?

2022-11-08 15:48 UTC, AnuragThePathak commented on src/components/Footer.js
> +  	 				<li><Link to="/">About</Link></li>
Does link not support /#about?

2022-11-09 12:41 UTC, enricopro commented on src/components/Footer.js
> +  	 				<li><Link to="/">About</Link></li>
Yes, it does support it and it has been fixed. Sorry, we got a misunderstaning before.😅
Now it should be fixed. Try to check it.

2022-11-12 09:19 UTC, enricopro commented
I revert to earlier indentation. Then, I changed some <Link> tag to <a>, because they were not working properly (they didn't take to the podcast section "/#podcast"). It seems to me that all buttons in NavBar.js, Header.js and Footer.js are working, try to check it.

2022-11-12 12:16 UTC, AnuragThePathak requested changes

2022-11-12 12:16 UTC, AnuragThePathak commented on src/components/Footer.js
> +  	 				<li><Link to="/">Home</Link></li>
I am doubtful about indentation and all in this section. Kindly confirm once that you didn't change anything.

2022-11-12 12:16 UTC, AnuragThePathak commented on src/components/Header.js
> +                <a href="/#podcast"><button className="header_button"> Check out our most recent podcast
It should use Link

2022-11-12 12:16 UTC, AnuragThePathak commented on src/components/Navbar.js
> +        <li className='navbar-item'><a href="/#podcast">Podcasts</a></li>
Use Link

2022-11-13 14:46 UTC, enricopro commented on src/components/Footer.js
> +  	 				<li><Link to="/">Home</Link></li>
The indentation is identical to the one you have used in the original file. You can check it.

2022-11-13 14:49 UTC, enricopro commented on src/components/Header.js
> +                <a href="/#podcast"><button className="header_button"> Check out our most recent podcast
As I told you in this comment (https://github.com/commclassroom/commclassroom/pull/111#issuecomment-1312421950), I used <a> tag since <Link> tag seems to do not work when I try to redirect to a specific section.

2022-11-13 14:49 UTC, enricopro commented on src/components/Navbar.js
> +        <li className='navbar-item'><a href="/#podcast">Podcasts</a></li>
As I told you in this comment (https://github.com/commclassroom/commclassroom/pull/111#issuecomment-1312421950), I used tag since tag seems to do not work when I try to redirect to a specific section.

2022-11-14 10:51 UTC, AnuragThePathak approved these changes
LGTM

2022-11-14 10:55 UTC, AnuragThePathak requested changes

2022-11-14 10:55 UTC, AnuragThePathak commented on src/components/Footer.js
> +  	 				<li><Link to="/#about">About</Link></li>
I think it will also require to use anchor tag only. Also kindly mark whatever completed as resolved.

2022-11-14 10:56 UTC, AnuragThePathak commented
Check the all the changes properly make any changes if required and then re-request for review.

2022-11-22 10:12 UTC, enricopro reviewed
I have checked all the changes and I think that all the broken links have been fixed.
@AnuragThePathak give me your opinion :)

2022-11-25 14:18 UTC, AnuragThePathak requested changes

2022-11-25 14:18 UTC, AnuragThePathak commented on src/components/Footer.js
> -  	 				<li><a href="#blog">Blog</a></li>
Footer usually contains page links if exists, not sections. In case of about we don't have one hence using that.

2022-12-22 13:10 UTC, closed without merging