Our Students work at section aliened
WeMakeDevs/wemakedevs pull request #274
Opened 2022-12-25 16:27 UTC by AbhiPatel10

## Fixes Issue

This PR fixes the following issues:

closes #267

## Changes proposed

Here comes all the changes proposed through this PR

Convert Heading All Capital Word to first letter in uppercase and the remaining letters in lowercase.

Change in css to add padding-block.

## Check List (Check all the boxes which are applicable) 

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

![image](https://user-images.githubusercontent.com/76242769/209475437-916f9870-e8c1-4216-86a5-5dc32d635b84.png)

Add all the screenshots which support your changes

2022-12-26 07:08 UTC, Chandraprakash-Darji commented
@AbhiPatel10 Add the 3 more companys `virtusa`, `samsung` and `cisco`.

2022-12-26 17:33 UTC, AbhiPatel10 commented
I Have added Above 3 company logos please check it.

![image](https://user-images.githubusercontent.com/76242769/209571998-14196b78-12a9-4911-bd15-9b49cc162d4e.png)

2022-12-26 18:01 UTC, bhavyastar requested changes
@AbhiPatel10 Hey Can you fix the latest logo size?

2022-12-27 05:50 UTC, AbhiPatel10 commented
Now looks good ?

![image](https://user-images.githubusercontent.com/76242769/209617576-3938e377-9f85-4060-81dd-c7639d513724.png)

2022-12-27 15:45 UTC, Chandraprakash-Darji commented
@bhavyastar what do you think about making all the logo's grayscale

2022-12-29 06:17 UTC, Chandraprakash-Darji commented
@AbhiPatel10 add `razorpay` to componay section

2022-12-29 16:10 UTC, ManishBisht777 commented on src/components/home/Work/index.jsx
> +        <div className={styles.workImg2}>
Instead of making a separate div for separate lines, we can include the images in `workimg` div and set flex-wrap:wrap

2022-12-29 17:55 UTC, AbhiPatel10 commented on src/components/home/Work/index.jsx
> +        <div className={styles.workImg2}>
> @AbhiPatel10 add `razorpay` to company section

Added `Razorpay` Logo

2022-12-29 17:55 UTC, AbhiPatel10 commented
> @AbhiPatel10 add `razorpay` to company section

Added `Razorpay` Logo.

2022-12-29 17:56 UTC, AbhiPatel10 commented on src/components/home/Work/index.jsx
> +        <div className={styles.workImg2}>
Yes I have remove second section and use the flexbox.

2023-01-01 10:03 UTC, AbhiPatel10 commented
![image](https://user-images.githubusercontent.com/76242769/210167082-341b2d47-1961-4beb-bf26-972a6f07f9b9.png)

2023-01-01 10:22 UTC, Chandraprakash-Darji commented
@AbhiPatel10 Thanks for the contribution

2023-01-01 10:22 UTC, merged

2023-01-01 13:24 UTC, AbhiPatel10 commented
It's my pleasure, looking forward to contribute more in WeMakeDevs 🚀

2023-01-01 13:25 UTC, AbhiPatel10 commented
> @AbhiPatel10 Thanks for the contribution

It's my pleasure, looking forward to contribute more in WeMakeDevs 🚀