Readme1
WeMakeDevs/wemakedevs pull request #293
Opened 2023-01-02 10:00 UTC by AbhiPatel10

## Fixes Issue

This PR fixes the following issues:

#50

## Changes proposed

I Change the Demo Screenshot With New Updated Website Screenshot.

Also Change About WemakeDevs.

Here comes all the changes proposed through this PR

## Check List (Check all the boxes which are applicable) 

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

Add all the screenshots which support your changes

![image](https://user-images.githubusercontent.com/76242769/210216724-8d73f1da-fc61-44ec-9fff-44cd6a4c38f5.png)

2023-01-06 10:25 UTC, siddhant-khisty approved these changes
LGTM

2023-01-06 14:00 UTC, shivam-sharma7 requested changes

2023-01-06 16:43 UTC, AbhiPatel10 commented on README.md
> +Our community provides a variety of<b> FREE hands-on computer science training</b> and <b>workshops</b> designed to help individuals develop practical skills through hands-on learning experiences. We
Done @shivam-sharma7

2023-01-07 04:28 UTC, shivam-sharma7 approved these changes
LGTM👌

2023-01-08 17:05 UTC, merged