⚒️Created scroll to top button for the site.
WeMakeDevs/wemakedevs pull request #406
Opened 2023-02-07 07:03 UTC by Sreejit-Sengupto

## Fixes Issue #360

This PR fixes the following issues:

closes #360

## Changes proposed

Here comes all the changes proposed through this PR
Created a button which will add a functionality using which the users can scroll to top of the page, just by clicking the button.

## Check List (Check all the boxes which are applicable) 

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Screenshots

Add all the screenshots which support your changes
![image](https://user-images.githubusercontent.com/69980616/217171580-fca1d773-29a4-4d6d-a5c8-282262c01763.png)

2023-02-07 12:39 UTC, Chandraprakash-Darji requested changes

2023-02-07 12:39 UTC, Chandraprakash-Darji commented on src/pages/CoursesPage.jsx
> +      <ScrollToTop />
Add to the `app.jsx`

2023-02-07 12:39 UTC, Chandraprakash-Darji commented on src/components/ScrollToTop/index.jsx
> +        <img src={scrllBtn} className={styles['btn--image']} />
instead of image use Icon from `react-icons`

2023-02-07 12:40 UTC, Chandraprakash-Darji commented
@Sreejit-Sengupto resolve conflicts

2023-02-07 14:22 UTC, Chandraprakash-Darji requested changes
Delete up png

2023-02-07 14:22 UTC, Chandraprakash-Darji commented on src/pages/CoursesPage.jsx
> +    <>
undo the page file

2023-02-07 14:28 UTC, Sreejit-Sengupto commented on src/pages/CoursesPage.jsx
> +    <>
Sorry! I didn't get it.

2023-02-07 16:01 UTC, Sreejit-Sengupto commented on src/pages/CoursesPage.jsx
> +    <>
Do you mean undo the changes that I made in the file?

2023-02-08 13:30 UTC, Chandraprakash-Darji requested changes

2023-02-08 13:30 UTC, Chandraprakash-Darji commented on src/pages/CoursesPage.jsx
> +    <>
Yes undo it

2023-02-08 14:00 UTC, Sreejit-Sengupto commented
It's compiling with warnings, should I make necessary changes?

2023-02-08 14:49 UTC, Chandraprakash-Darji requested changes

2023-02-08 14:49 UTC, Chandraprakash-Darji commented on src/pages/CoursesPage.jsx
> +      <Layout content={CoursesPageContent}>
Still has changes

2023-02-08 14:49 UTC, Chandraprakash-Darji commented on src/pages/Events.jsx
>    return (
Undo this

2023-02-08 14:49 UTC, Chandraprakash-Darji commented on src/pages/Hashnode.jsx
> +    <>
Undo this file

2023-02-08 14:49 UTC, Chandraprakash-Darji commented on src/pages/SingleCoursePage.jsx
> +    <>
Undo this file

2023-02-08 14:50 UTC, Chandraprakash-Darji commented
> It's compiling with warnings, should I make necessary changes?

@Sreejit-Sengupto What kind of error?

2023-02-08 15:19 UTC, Chandraprakash-Darji commented
Just save it. It will fix prettier erro

2023-02-08 19:12 UTC, Chandraprakash-Darji commented
@Sreejit-Sengupto update the screenshot

2023-02-08 19:13 UTC, Sreejit-Sengupto commented
> @Sreejit-Sengupto update the screenshot

Just a second

2023-02-08 19:17 UTC, Sreejit-Sengupto commented
Updated the screenshot

2023-02-08 19:23 UTC, Chandraprakash-Darji requested changes

2023-02-08 19:23 UTC, Chandraprakash-Darji commented on src/components/ScrollToTop/index.module.css
> +  border: none;
Add the z-index to be above the banner

2023-02-08 19:23 UTC, Chandraprakash-Darji commented on src/components/ScrollToTop/index.module.css
> +  height: 4vw;
remove height and width. Instead just increase the font because it is font. and add the color purple

2023-02-08 19:23 UTC, Chandraprakash-Darji commented on src/components/ScrollToTop/index.module.css
> +  height: 4vw;
not purple, primary color

2023-02-08 19:23 UTC, Chandraprakash-Darji commented on src/components/ScrollToTop/index.jsx
> +    <div className={styles['scroll--to--top--button']}>
use intersection observer and make the button show when user start the scrolling

2023-02-08 19:27 UTC, Sreejit-Sengupto commented
Ok will work on this! Will reach out if I need help.

2023-02-08 20:19 UTC, Chandraprakash-Darji commented
@Sreejit-Sengupto I am ready to help out. reach out on discord Chandra#4312

2023-02-08 20:19 UTC, Sreejit-Sengupto commented
Sure!

2023-02-09 03:49 UTC, ziaulkadri approved these changes

2023-02-09 03:50 UTC, ziaulkadri commented
good feature looks nice to me

2023-02-09 17:47 UTC, Chandraprakash-Darji requested changes

2023-02-09 17:47 UTC, Chandraprakash-Darji commented on src/components/ScrollToTop/index.jsx
> +    });
If you add any event listner to the component then you have to remove also when it demount

2023-02-10 13:46 UTC, Sreejit-Sengupto commented on src/components/ScrollToTop/index.jsx
> +    });
You mean that I should remove the event-listener once the button appears?

2023-02-11 13:35 UTC, Sreejit-Sengupto commented on src/components/ScrollToTop/index.jsx
> +    });
What if I do window.removeEventListner() in the else block after setToTop(false)
Something like this :-
`else {
     setgoToTop(false);
     window.removeEventListener('scroll');
}`

2023-02-11 14:51 UTC, Chandraprakash-Darji commented on src/components/ScrollToTop/index.jsx
> +    });
When we add the scroll event listener to the component then we have to remove it when we demount it. If we do not do this then when it will rerender it will add again and it affect the website performance. Read the docs https://reactjs.org/docs/hooks-effect.html#effects-with-cleanup

2023-02-11 14:57 UTC, Sreejit-Sengupto commented on src/components/ScrollToTop/index.jsx
> +    });
```
useEffect(() => {
    window.addEventListener('scroll', () => {
      if (window.scrollY > 200) {
        setgoToTop(true);
      } else {
        setgoToTop(false);
      }
    });
    return () => {
      window.removeEventListener('scroll');
    };
  }, []);
```

Will this code work? I tried the code you used you sent!

2023-02-11 20:16 UTC, Chandraprakash-Darji commented on src/components/ScrollToTop/index.jsx
> +    });
You have to pass the callback function the removeEventListener function.

2023-02-11 20:17 UTC, Chandraprakash-Darji commented on src/components/ScrollToTop/index.jsx
> +    });
First store the callback function and then pass it to the addEventListener and removeEventListener

2023-02-12 07:30 UTC, Sreejit-Sengupto commented on src/components/ScrollToTop/index.jsx
> +    });
Means I should store the if-else statement in a variable and then pass them in addEventListner and removeEventListner?

2023-02-12 17:09 UTC, Sreejit-Sengupto commented on src/components/ScrollToTop/index.jsx
> +    });
```
const showBtn = () => {
    if (window.scrollY > 200) {
      setgoToTop(true);
    } else {
      setgoToTop(false);
    }
  };
  useEffect(() => {
    window.addEventListener('scroll', showBtn);
    return () => {
      window.removeEventListener('scroll', showBtn);
    };
  }, []);
```

Will this piece of code work?

2023-02-12 17:28 UTC, Chandraprakash-Darji commented on src/components/ScrollToTop/index.jsx
> +    });
Yes it work

2023-02-12 17:29 UTC, Sreejit-Sengupto commented on src/components/ScrollToTop/index.jsx
> +    });
Ok then I am pushing the code!

2023-02-12 17:41 UTC, Chandraprakash-Darji requested changes

2023-02-12 17:41 UTC, Chandraprakash-Darji commented on src/pages/SingleCoursePage.jsx
> +import Layout, { Testimonials } from '../components/layout';
undo this

2023-02-12 17:41 UTC, Chandraprakash-Darji commented on src/pages/HomePage.jsx
> +} from '../components/home';
Undo this change

2023-02-12 17:41 UTC, Chandraprakash-Darji commented on src/pages/Hashnode.jsx
> +import Layout from '../components/layout';
undo this changes

2023-02-12 17:41 UTC, Chandraprakash-Darji commented on src/components/ScrollToTop/index.jsx
> +    });
good

2023-02-12 18:15 UTC, Chandraprakash-Darji approved these changes

2023-02-12 18:16 UTC, Chandraprakash-Darji commented
@Sreejit-Sengupto great contribution. Congrats on your first contribution to WeMakeDevs.

2023-02-12 18:21 UTC, Sreejit-Sengupto commented
Thanks to you! It was definitely not possible without your help and assistance throughout. Looking forward to contribute more!😃

2023-02-13 14:25 UTC, merged