SVG background to the Section ~ hero-header-container
WeMakeDevs/wemakedevs pull request #428
Opened 2023-02-12 11:58 UTC by PKM777

## Minor Enhancement

Added a simple SVG background to hero-header-container

## Screenshots

![design0](https://user-images.githubusercontent.com/99317905/218309234-73190962-aeb1-4555-97cc-d318865d4c87.PNG)
![design1](https://user-images.githubusercontent.com/99317905/218309236-80159427-7c9d-4ce7-952c-b37c8c34291e.PNG)

2023-02-12 16:18 UTC, ArslanYM commented
@PKM777  looks cool!

2023-02-12 17:38 UTC, Chandraprakash-Darji commented
@PKM777 When ever is there any idea, Just dicuss with the team first

2023-02-12 17:38 UTC, Chandraprakash-Darji commented
@AnuragThePathak How it is?

2023-02-12 17:43 UTC, Chandraprakash-Darji requested changes

2023-02-12 17:43 UTC, Chandraprakash-Darji commented on src/components/home/Hero/index.module.css
> +  background-image: url('../../../assets/images/chaos.svg') !important;
don't use imporatant

2023-02-12 18:05 UTC, AnuragThePathak commented
Fair enough ig.

2023-02-12 18:53 UTC, PKM777 commented on src/components/home/Hero/index.module.css
> +  background-image: url('../../../assets/images/chaos.svg') !important;
it doesn't work without !important ! :( do you know why ?

2023-02-16 13:43 UTC, Chandraprakash-Darji commented on src/components/home/Hero/index.module.css
> +  background-image: url('../../../assets/images/chaos.svg') !important;
@PKM777 add to other pages also

2023-02-16 13:49 UTC, Chandraprakash-Darji commented
@PKM777 remove important and just increase specificity

CSS of hero section
```css
body .section.header-container {
  height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  text-align: center;
  background-image: url('../../../assets/images/chaos.svg');
  background-repeat: no-repeat;
  background-position: center;
  background-size: cover;
}
```

JSX for the Component
```jsx
  <section className={clsx(styles.section, styles['header-container'])}>
 ```
  update first line

2023-02-16 16:34 UTC, PKM777 commented
> @PKM777 remove important and just increase specificity
> 
> CSS of hero section
> 
> ```css
> body .section.header-container {
>   height: 100vh;
>   display: flex;
>   align-items: center;
>   justify-content: center;
>   text-align: center;
>   background-image: url('../../../assets/images/chaos.svg');
>   background-repeat: no-repeat;
>   background-position: center;
>   background-size: cover;
> }
> ```
> 
> JSX for the Component
> 
> ```js
>   <section className={clsx(styles.section, styles['header-container'])}>
> ```
> 



> @PKM777 remove important and just increase specificity
> 
> CSS of hero section
> 
> ```css
> body .section.header-container {
>   height: 100vh;
>   display: flex;
>   align-items: center;
>   justify-content: center;
>   text-align: center;
>   background-image: url('../../../assets/images/chaos.svg');
>   background-repeat: no-repeat;
>   background-position: center;
>   background-size: cover;
> }
> ```
> 
> JSX for the Component
> 
> ```js
>   <section className={clsx(styles.section, styles['header-container'])}>
> ```
> 
> update first line

this doesn't work

2023-02-16 20:32 UTC, Chandraprakash-Darji commented
@PKM777 have you updated the JSX file?

2023-02-19 05:10 UTC, Chandraprakash-Darji commented
@PKM777 is it working?

2023-02-26 10:02 UTC, AnuragThePathak commented
@PKM777 are you still working?

2023-03-01 07:43 UTC, AnuragThePathak commented
Closing due to inactivity.

2023-03-01 07:43 UTC, closed without merging