Add the skeleton loader in the event sections
WeMakeDevs/wemakedevs pull request #435
Opened 2023-02-15 16:53 UTC by staticGuru

## Feature implementation

Add the skeleton loader in the event sections!!
Fix the lazy tweet card issues in the event sections.

2023-02-16 14:33 UTC, Chandraprakash-Darji commented
@staticGuru share the video output or the screenshot

2023-02-16 16:49 UTC, staticGuru commented
> 

![skeleton Integrations](https://user-images.githubusercontent.com/79417096/219431974-d1290299-05e4-4224-bb5f-9066ad6b5270.png)
I implement the skeleton loader for fix the lazy tweeter post rendering.

2023-02-16 16:50 UTC, staticGuru commented
@Chandraprakash-Darji Review the changes and do the needful!!

2023-02-16 20:39 UTC, Chandraprakash-Darji commented
@staticGuru great contribution to website. Just descrese the height to 50vh and create a component that will take the list of tweetid and render this becuse this is used on `/events` page, `/courses` and courses specific page also

2023-02-16 20:39 UTC, Chandraprakash-Darji commented
@staticGuru Thanks

2023-02-17 16:11 UTC, staticGuru commented
@Chandraprakash-Darji 
I changed the skeleton component and replaced it with all tweet cards.
Review on it and let me know.

2023-02-19 05:09 UTC, Chandraprakash-Darji requested changes

2023-02-19 05:09 UTC, Chandraprakash-Darji commented on src/components/SkeletonCard/index.jsx
> +function InlineWrapperWithMargin({ children }) {
What is the use of this component? Add the comment

2023-02-19 05:09 UTC, Chandraprakash-Darji commented on src/components/SkeletonCard/index.jsx
> +      {hideTweetPost ? (
make the condition rendering, show loader or the Carousel

2023-02-19 05:09 UTC, Chandraprakash-Darji commented on src/components/SkeletonCard/index.jsx
> +      {hideTweetPost ? (
Use the ternery operator

2023-02-19 05:09 UTC, Chandraprakash-Darji commented on src/components/SkeletonCard/index.jsx
> +function SkeletonCard({ tweetId, options }) {
give the name of TweetCarousael: name should be simple

2023-02-19 18:23 UTC, staticGuru commented on src/components/SkeletonCard/index.jsx
> +function InlineWrapperWithMargin({ children }) {
Actually, This component helps to provide the lazy loading for tweet cards and show the tweet loader to provide a better UI/UX.

2023-02-28 11:56 UTC, staticGuru commented on src/components/SkeletonCard/index.jsx
> +      {hideTweetPost ? (
@Chandraprakash-Darji I done the mentioned changes on the features and created the pull requests.
kindly verify it and merge it.

2023-02-28 11:57 UTC, staticGuru commented on src/components/SkeletonCard/index.jsx
> +function SkeletonCard({ tweetId, options }) {
@Chandraprakash-Darji I change the components name in the readable formats.
kindly check and verify the PR.

2023-02-28 12:13 UTC, Chandraprakash-Darji commented
@staticGuru there are some conflict that should be resolved

2023-02-28 12:26 UTC, staticGuru commented
> @staticGuru there are some conflict that should be resolved

@Chandraprakash-Darji I carefully checked the conflicts and fix those conflicts.
kindly review once and merge it

2023-03-01 12:29 UTC, staticGuru commented
@Chandraprakash-Darji @Bawanthathilan  There are any issues in the merging?
kindly let me know, I will work on it

2023-03-01 14:21 UTC, Chandraprakash-Darji requested changes

2023-03-01 14:21 UTC, Chandraprakash-Darji commented on src/components/hashnode/HowTakePart/index.jsx
>  import ColumnSection from '@/components/layout/ColumnSection';
there is similar imports check line 2

2023-03-01 14:21 UTC, Chandraprakash-Darji commented on src/components/hashnode/HowTakePart/index.jsx
>  import ColumnSection from '@/components/layout/ColumnSection';
there is similar imports check line 2

2023-03-01 14:21 UTC, Chandraprakash-Darji commented on src/components/hashnode/HowTakePart/index.jsx
> +      <TweetCarousael tweetId={tweetId} options={{ theme: 'dark' }} />
instead of passing the `tweetId` pass `prizetweetid` which are imported

2023-03-01 14:21 UTC, Chandraprakash-Darji commented on src/components/home/events/index.jsx
> +        tweetId={tweetId}
instead of passing the `tweetId` pass `prizetweetid` which are imported

2023-03-01 14:21 UTC, Chandraprakash-Darji commented on src/components/layout/Testimonials/index.jsx
> +        options={{ theme: 'dark', conversation: 'none' }}
import prizetweetid and pass it

2023-03-01 14:21 UTC, Chandraprakash-Darji commented on src/App.jsx
> +import './styles/resets.css';
use absolute import start with `@`

2023-03-01 14:21 UTC, Chandraprakash-Darji commented on src/components/TweetCarousael/index.jsx
> +            paddingBottom: '5rem',
remove padding bottom so it will not extra space to section

2023-03-01 14:21 UTC, Chandraprakash-Darji commented on src/components/coursespage/Testimonial/index.jsx
> +      <TweetCarousael
this should be inside the div

2023-03-01 14:21 UTC, Chandraprakash-Darji commented on src/components/hashnode/HowTakePart/index.jsx
> +      <TweetCarousael tweetId={tweetId} options={{ theme: 'dark' }} />
move into the div

2023-03-01 14:21 UTC, Chandraprakash-Darji commented on src/components/layout/Testimonials/index.jsx
> +        options={{ theme: 'dark', conversation: 'none' }}
move into the div

2023-03-04 17:23 UTC, staticGuru commented
@Chandraprakash-Darji 
I Done the requested changes.
Kindly verify on it.

2023-03-05 06:15 UTC, Chandraprakash-Darji requested changes

2023-03-05 06:15 UTC, Chandraprakash-Darji commented on src/components/hashnode/HowTakePart/index.jsx
> +      <TweetCarousael tweetId={prizetweetid} options={{ theme: 'dark' }} />
You have missed the changes in this file

2023-03-05 10:19 UTC, staticGuru commented
@Chandraprakash-Darji I changed the file.
Kindly check and verify it.

2023-03-05 19:05 UTC, Chandraprakash-Darji approved these changes

2023-03-05 19:06 UTC, Chandraprakash-Darji commented
@staticGuru Great work, You have good patience for working on it

2023-03-06 15:59 UTC, merged