Improves website accessibility score
WeMakeDevs/wemakedevs pull request #443
Opened 2023-02-17 16:11 UTC by VijayalakshmiGanesh

## Fixes Issue

This PR fixes the following issues:

closes #336 

## Changes proposed

Fixed the following issues to improve website accessibility score from 79 to 97 by adding **aria-label** wherever necessary
1. 
![image](https://user-images.githubusercontent.com/104077094/219703479-b9551569-b280-4bb8-ba22-cd052b78d58e.png)
2. 
![image](https://user-images.githubusercontent.com/104077094/219703628-890322da-9fc7-440b-acea-13840fe7813e.png)
3. 
![image](https://user-images.githubusercontent.com/104077094/219703816-cc388655-a868-4f19-80f3-477ff38690e0.png)

## Check List (Check all the boxes which are applicable) 

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

Output verified using Chrome LightHouse Audit.
![image](https://user-images.githubusercontent.com/104077094/219704474-97053394-0359-40ed-92d4-0f9d5868d6a2.png)

2023-02-19 05:04 UTC, Chandraprakash-Darji commented
@VijayalakshmiGanesh make the highlight text yellow. becuse on hashnode page it is used yellow

2023-02-19 11:23 UTC, VijayalakshmiGanesh commented
Output Verified in WAVE tool
![image](https://user-images.githubusercontent.com/104077094/219944817-c560a8cb-adaf-468f-b9b7-9b9ac8083eee.png)

2023-02-20 01:38 UTC, Chandraprakash-Darji commented
@VijayalakshmiGanesh Scroll to top button has not descriptive text, add that

2023-02-20 01:38 UTC, Chandraprakash-Darji commented
@VijayalakshmiGanesh Great work

2023-02-20 01:39 UTC, Chandraprakash-Darji commented
Also add the alt text for the image
![image](https://user-images.githubusercontent.com/93640141/219990123-9b47c1e2-d2a3-4ddb-ad5c-94df8d10976a.png)
it is on the hasnode page

2023-02-20 01:42 UTC, Chandraprakash-Darji requested changes

2023-02-20 01:42 UTC, Chandraprakash-Darji commented on src/components/home/Hero/index.jsx
> +          <span className='highlight highlight--yelow'>
fix the typo of yellow

2023-02-20 01:42 UTC, Chandraprakash-Darji commented on src/styles/root.css
>    --primary-hover: 64, 41, 209; /* #4029d1 */
don't play with primary color

2023-02-20 01:42 UTC, Chandraprakash-Darji commented on src/styles/root.css
>    --primary-hover: 64, 41, 209; /* #4029d1 */
Just reset back to old, because color you have set is not vibrant

2023-02-20 05:54 UTC, VijayalakshmiGanesh commented on src/styles/root.css
>    --primary-hover: 64, 41, 209; /* #4029d1 */
Is there any other alternative color that we could use to improve the contrast here
 or would you prefer that we leave the both content and primary color as is for the time being?

2023-02-20 08:00 UTC, VijayalakshmiGanesh commented on src/components/home/Hero/index.jsx
> +          <span className='highlight highlight--yelow'>
Fixed. Kindly check

2023-02-20 08:07 UTC, VijayalakshmiGanesh commented on src/styles/root.css
>    --primary-hover: 64, 41, 209; /* #4029d1 */
I have reverted the changes. please check

2023-02-20 15:38 UTC, Chandraprakash-Darji commented on src/styles/root.css
>    --primary-hover: 64, 41, 209; /* #4029d1 */
Let;s let it be for time being

2023-02-20 15:44 UTC, Chandraprakash-Darji requested changes

2023-02-21 04:41 UTC, VijayalakshmiGanesh commented on src/components/links/UnstyledLink.jsx
> +          'aria-label': ariaLabel,
Removed as per your comments. Please check

2023-02-21 15:07 UTC, AnuragThePathak commented
@VijayalakshmiGanesh fix the error occurring on running the Nodejs action.

2023-02-21 16:35 UTC, VijayalakshmiGanesh commented
> @VijayalakshmiGanesh fix the error occurring on running the Nodejs action.

Please check now

2023-02-21 19:12 UTC, Chandraprakash-Darji approved these changes

2023-02-21 19:14 UTC, merged