updated Readme.md Installation step
WeMakeDevs/wemakedevs pull request #451
Opened 2023-02-20 07:54 UTC by JasonDsouza212

This PR fixes the following issues:
- The missing step during installation has been added. 
-  Unnecessary spaces have been removed

## Changes made
- The installation process missed the step of changing the directory after cloning the repository to execute 'npm i'
- This pull request resolves the issue by removing unnecessary spaces and ensuring there are no spaces after the backtick.

## Check List (Check all the boxes which are applicable) 

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x]  All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

## Before
![Screenshot from 2023-02-20 13-17-48](https://user-images.githubusercontent.com/74404894/220044246-6c763a0f-b2f4-4fd6-be60-46d58404d5d7.png)

## After
![Screenshot from 2023-02-20 13-17-29](https://user-images.githubusercontent.com/74404894/220044384-5cd24d0c-d15a-4465-aae1-8fe03f141eea.png)

2023-02-20 15:58 UTC, Chandraprakash-Darji requested changes

2023-02-20 15:58 UTC, Chandraprakash-Darji commented on README.md
> +4. Run `npm i` Or `npm install` to install all dependencies
make `npm ci` and `npm clean-install` that will not generate the new package-lock file

2023-02-20 16:00 UTC, Chandraprakash-Darji requested changes

2023-02-21 15:14 UTC, AnuragThePathak commented on README.md
> +6. Visit `https://localhost:3000` to view the application
Please note that it should be http not https

2023-02-21 16:05 UTC, JasonDsouza212 commented
I think everything looks good now

2023-02-21 19:13 UTC, Chandraprakash-Darji requested changes

2023-02-21 19:13 UTC, Chandraprakash-Darji commented on README.md
> +6. Visit [http://localhost:3000](http://localhost:3000) to view the application
make it https

2023-02-21 19:14 UTC, Chandraprakash-Darji approved these changes

2023-02-24 20:57 UTC, merged