Fixed the bug on Not Found Page
WeMakeDevs/wemakedevs pull request #463
Opened 2023-02-24 15:13 UTC by Varunvaru524

## Fixes Issue

This PR fixes the following issues:

closes #462

## Changes proposed

1. Fixed the bug on the not found page where 404! and the sentence below it is attached together in the mobile view.
2. Changed the background color of the Back To Home button so it appears clearly as a button.

## Check List (Check all the boxes which are applicable) 

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

Add all the screenshots which support your changes
![Screenshot 2023-02-24 203154](https://user-images.githubusercontent.com/101904494/221214703-d25e3795-c852-4024-906f-d57d6c943d9a.png)

2023-02-24 20:55 UTC, Chandraprakash-Darji requested changes

2023-02-24 20:55 UTC, Chandraprakash-Darji commented on src/pages/ErrorPage/index.module.css
> +  /* background: transparent; */
Remove the button Styles and use Normal Primary button which is used everywhere

2023-02-25 07:31 UTC, Varunvaru524 commented
Changed the button to Primary button as requested
![Web capture_25-2-2023_13020_localhost](https://user-images.githubusercontent.com/101904494/221344878-94c309ce-00ab-48f0-ace9-e9951e9d0f90.jpeg)

2023-02-25 07:48 UTC, Chandraprakash-Darji requested changes

2023-02-25 07:48 UTC, Chandraprakash-Darji commented on src/pages/ErrorPage/index.jsx
> +          <ArrowLink as={ButtonLink}>Back To Home</ArrowLink>
remove backToHome FN. becuse you can just pass href='/' to the Link

2023-02-25 07:48 UTC, Chandraprakash-Darji commented on src/pages/ErrorPage/index.module.css
>  .btn {
remove the css lines

2023-02-25 09:13 UTC, Varunvaru524 commented on src/pages/ErrorPage/index.jsx
> +          <ArrowLink as={ButtonLink}>Back To Home</ArrowLink>
Yeah I have tried that but the problem is when the user clicks back to go to previous page, it will take straight to the Not Found Page. But with backToHome FN it will replace the history by skipping the Not Found Page. 

Any way its your call, if you want me to pass href i will??

2023-02-25 09:13 UTC, Varunvaru524 commented on src/pages/ErrorPage/index.module.css
>  .btn {
Sure

2023-02-25 16:34 UTC, Chandraprakash-Darji commented on src/pages/ErrorPage/index.jsx
> +          <ArrowLink as={ButtonLink}>Back To Home</ArrowLink>
just send the user to homepage

2023-02-25 18:37 UTC, Chandraprakash-Darji requested changes

2023-02-25 18:37 UTC, Chandraprakash-Darji commented on src/pages/ErrorPage/index.jsx
> +          Back To Home
make `T` and `H` small

2023-02-25 18:37 UTC, Chandraprakash-Darji commented on src/pages/ErrorPage/index.jsx
> +          Back To Home
Just update the screenshot

2023-02-25 19:53 UTC, Varunvaru524 commented
![Web capture_26-2-2023_05543_localhost](https://user-images.githubusercontent.com/101904494/221376914-844c2cfe-1b0f-4780-8a4a-cd9f084cdf49.jpeg)

2023-02-26 04:43 UTC, Chandraprakash-Darji approved these changes

2023-02-26 04:44 UTC, merged