Update the logo in the header section
WeMakeDevs/wemakedevs pull request #464
Opened 2023-02-25 05:08 UTC by SohamRoy-01

## Fixes Issue

This PR fixes the following issues:

closes #issue-number

## Changes proposed

Here comes all the changes proposed through this PR

## Check List (Check all the boxes which are applicable) 

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

Add all the screenshots which support your changes

2023-02-25 05:10 UTC, SohamRoy-01 commented
@Chandraprakash-Darji Due to merge conflicts I close the PR and I removed the small logo and update it accordingly...

2023-02-25 07:49 UTC, Chandraprakash-Darji commented
@SohamRoy-01 When you create the PR, just make share the screenshot

2023-02-26 07:00 UTC, SohamRoy-01 commented
I added the screenshot @Chandraprakash-Darji

2023-02-26 09:41 UTC, siddhant-khisty approved these changes
LGTM.
cc @AnuragThePathak

2023-02-26 10:33 UTC, AnuragThePathak commented
@SohamRoy-01 kindly fix the merge conflicts and we are good to merge it.

2023-02-26 13:15 UTC, SohamRoy-01 commented
Fixed @AnuragThePathak

2023-02-27 04:09 UTC, Chandraprakash-Darji requested changes

2023-02-27 04:09 UTC, Chandraprakash-Darji commented on README.md
> +  <a href="https://github.com/commclassroom/commclassroom/issues"><img alt="GitHub issues" src="https://img.shields.io/github/issues/commclassroom/commclassroom"></a>
This link should be of wemakedevs not the commclassrom

2023-02-27 06:00 UTC, SohamRoy-01 commented on README.md
> +  <a href="https://github.com/commclassroom/commclassroom/issues"><img alt="GitHub issues" src="https://img.shields.io/github/issues/commclassroom/commclassroom"></a>
changed done,

2023-02-27 12:01 UTC, Chandraprakash-Darji approved these changes

2023-02-27 14:32 UTC, merged