Updated content in home page
WeMakeDevs/wemakedevs pull request #481
Opened 2023-03-08 17:09 UTC by Parvej2001

## Fixes Issue

This PR fixes the following issues:
Updated content in home page
closes #issue-number

## Changes proposed

Here comes all the changes proposed through this PR

## Check List (Check all the boxes which are applicable) 

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

Add all the screenshots which support your changes

2023-03-09 12:41 UTC, SuperAayush requested changes
Here are some of my suggestions!!

2023-03-10 13:06 UTC, siddhant-khisty commented on src/components/home/Content/index.jsx
> +              leaders and members.
The Open Source Cafe podcast is committed to presenting the narratives, experiences, insights, and techniques of outstanding leaders and members within the technical community.

2023-03-10 13:06 UTC, siddhant-khisty commented on src/components/home/Content/index.jsx
> +              individuals who have achieved great heights in their careers.
`accomplished individuals`*

2023-03-10 13:06 UTC, siddhant-khisty commented on src/components/home/Content/index.jsx
> +              cloud native technology.
Check out the Kubeletter, our monthly newsletter covering updates, insights, and sharing valuable resources around all things cloud native.

2023-03-10 13:06 UTC, siddhant-khisty commented on src/components/home/Content/index.jsx
> +              different technologies have impacted enterprises.
Explore our collection of case studies, featuring real-world examples of how different technologies have impacted developers, making their lives easier.

2023-03-10 13:06 UTC, siddhant-khisty commented on src/components/home/Mentorship/index.jsx
> +        your skills.
```
including educational resources, domain roadmaps, communities to join, and many great opportunities to improve your abilities.
```

2023-03-10 13:06 UTC, siddhant-khisty commented on src/components/home/Mentorship/index.jsx
> +        We offer personalized roadmaps to help you stay on track, whether you
```suggestion
        We offer domain-specific roadmaps to help you stay on track, whether you
```

2023-03-10 13:06 UTC, siddhant-khisty commented on src/components/home/about/index.jsx
> +          inclusive community.{' '}
We provide free practical training, mentorship programs, many learning opportunities, and a welcoming community with over 60,000 members.

2023-03-10 13:06 UTC, siddhant-khisty commented on src/components/home/about/index.jsx
> +          We also organize regular weekly and monthly events to help individuals
```suggestion
          We also organize regular events to help individuals
```

2023-03-10 13:06 UTC, siddhant-khisty commented on src/components/home/courses/index.jsx
> +          quality, yet they are entirely free for all learners.
`completely free for everyone, without sacrificing on quality`*

2023-03-10 13:06 UTC, siddhant-khisty commented on src/components/home/events/index.jsx
> +          fun-filled events without compromising on quality.
```suggestion
          fun-filled events that do not have any entry-barriers without compromising on quality.
```

2023-03-10 13:06 UTC, siddhant-khisty commented on src/components/home/events/index.jsx
> +          prizes and goodies!
```suggestion
          Don't miss the chance to explore a range of events, improve your skills and win amazing
          prizes and goodies!
```

2023-03-24 10:43 UTC, tejash023 commented
hi @SuperAayush Can I work on this? or is this completed?

2023-04-09 07:20 UTC, closed without merging