Added hover effect to footer external links
WeMakeDevs/wemakedevs pull request #485
Opened 2023-03-12 18:12 UTC by Varunvaru524

## Fixes Issue

This PR fixes the following issues:

closes #484 

## Changes proposed

Added the navbar hover animation to the footer external links so that the links will be more visible and the style of the project will stay consistent throughout.

## Check List (Check all the boxes which are applicable) 

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

https://user-images.githubusercontent.com/101904494/224563944-8940545a-b8fe-4f3d-b0e8-67cee3b1e368.mp4

2023-03-14 13:31 UTC, Chandraprakash-Darji commented
@Varunvaru524  great work

2023-03-14 13:31 UTC, Chandraprakash-Darji commented
Fix the conflicts

2023-03-16 07:57 UTC, Varunvaru524 reviewed
Fixed all the conflicts

2023-03-20 18:46 UTC, Chandraprakash-Darji requested changes

2023-03-20 18:46 UTC, Chandraprakash-Darji commented on README.md
> -
undo update in the readme

2023-03-20 18:46 UTC, Chandraprakash-Darji commented on src/components/layout/Footer/index.module.css
> +  padding-bottom: 3px;
share the preview without this

2023-03-21 09:20 UTC, Varunvaru524 commented on src/components/layout/Footer/index.module.css
> +  padding-bottom: 3px;
Without 3px Padding

https://user-images.githubusercontent.com/101904494/226563421-8ff62c03-3a1d-4d4f-8074-c785a8010c13.mp4

2023-03-21 09:38 UTC, Varunvaru524 commented on README.md
> -
Undid Readme file
[8ec396b](https://github.com/WeMakeDevs/wemakedevs/pull/485/commits/8ec396bcc71352ae2cfc95c4e040bcdd632fddec)

2023-03-21 12:22 UTC, Chandraprakash-Darji approved these changes

2023-03-22 05:14 UTC, Varunvaru524 commented
Is this PR ready to merge?

2023-03-25 07:14 UTC, merged