Grammatically updated the 'Mentorship' tab.
WeMakeDevs/wemakedevs pull request #495
Opened 2023-03-18 20:18 UTC by RaunakN28

## Fixes Issue

This PR fixes the following issues:

Small grammatical update to the text in the "Mentorship" tab.

closes #issue-number

## Changes proposed

Here comes all the changes proposed through this PR

## Check List (Check all the boxes which are applicable) 

- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

Add all the screenshots which support your changes

2023-03-19 16:21 UTC, siddhant-khisty requested changes

2023-03-19 16:21 UTC, siddhant-khisty commented on src/components/home/Mentorship/index.jsx
> +          A complete solution to address all of your mentoring requirements.
```suggestion
          A comprehensive solution to address all of your mentoring requirements.
```

2023-03-19 16:21 UTC, siddhant-khisty commented on src/components/home/Mentorship/index.jsx
> +          Roadmaps that will guide you towards a successful career,
```suggestion
          Roadmaps to guide you towards a successful career,
```

2023-03-21 22:51 UTC, siddhant-khisty approved these changes
Lgtm

2023-03-25 08:14 UTC, AnuragThePathak commented
@RaunakN28 you'll need to fix the errors.

2023-03-25 15:17 UTC, RaunakN28 commented
@siddhant-khisty I need some help fixing the errors.

2023-03-26 08:57 UTC, AnuragThePathak commented
@RaunakN28 mention what help you need directly.

2023-03-27 05:18 UTC, siddhant-khisty commented
@RaunakN28 Looks like a linting error. You can use the prettier extension in VScode and simply run it to fix this.

2023-04-04 17:04 UTC, AnuragThePathak commented
@RaunakN28 are you still working?

2023-04-05 16:16 UTC, RaunakN28 commented
@AnuragThePathak No, since I don't have any knowledge regarding solving these errors.

2023-04-05 16:28 UTC, AnuragThePathak commented
@RaunakN28 as far I understand, you simply had to insert a new line after 22nd line in src/components/home/Mentorship/index.jsx

Try doing that and push or simply inform us if you are still confused/unable to do that.

2023-04-05 16:30 UTC, RaunakN28 commented
@AnuragThePathak Ok. I'll try my best.

2023-04-05 17:26 UTC, RaunakN28 commented
@AnuragThePathak I guess it worked. Thanks for helping.

2023-04-06 06:16 UTC, AnuragThePathak commented
@RaunakN28 great job now it's time to fix the conflicts. If you know how to, do it in your own way.

If not use `git pull upstream main --no-rebase` and git or some editor will open (as per your settings, you need to save it as done in your editor and it should conflict merge process.

2023-04-10 19:39 UTC, merged