Solved: Redesigned work section #539
WeMakeDevs/wemakedevs pull request #540
Opened 2023-04-06 20:37 UTC by harmanbatheja15

## Fixes Issue #539 

## Check List (Check all the boxes which are applicable) 

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Current Design
<img width="2240" alt="Screenshot 2023-04-07 at 1 39 17 AM" src="https://user-images.githubusercontent.com/66913564/230488601-bc4f31db-e818-49ba-a291-bc640cb18aa6.png">

## New Design
<img width="2240" alt="Screenshot 2023-04-07 at 1 43 27 AM" src="https://user-images.githubusercontent.com/66913564/230488512-4ac4bcb7-64d7-407f-88ba-6f4e4bb32b10.png">

2023-04-07 18:12 UTC, Chandraprakash-Darji commented on src/components/PageComp/HomePage/Work.jsx
> +                  alt=''
Add alt attribute as company name.

2023-04-07 18:13 UTC, Chandraprakash-Darji requested changes

2023-04-07 18:13 UTC, Chandraprakash-Darji commented on src/components/PageComp/HomePage/Work.jsx
> +    <>
React fragment is not required

2023-04-07 18:13 UTC, Chandraprakash-Darji commented on src/components/PageComp/HomePage/Work.jsx
> +      <section className='mb-10 py-10'>
remove mb--10

2023-04-07 19:50 UTC, harmanbatheja15 commented
I have made the changes as per your request, but after removing `mb-10`, the heading below it is now touching the above content and there is no spacing between them. I have attached a screenshot for your reference.

<img width="2240" alt="Screenshot 2023-04-08 at 1 12 21 AM" src="https://user-images.githubusercontent.com/66913564/230668478-2dcbc708-9733-44df-80b0-a9d0b92ac374.png">

2023-04-10 17:16 UTC, Chandraprakash-Darji requested changes

2023-04-10 17:16 UTC, Chandraprakash-Darji commented on src/components/PageComp/HomePage/Work.jsx
> +    <section className='py-10'>
Let be div, the reason for that is because Course, work, and testimonials are connected. after making it div then you don't need for mb

2023-04-13 16:18 UTC, Chandraprakash-Darji requested changes

2023-04-13 16:18 UTC, Chandraprakash-Darji commented on src/components/PageComp/HomePage/Work.jsx
> +              className='m-4 h-20 w-48 rounded-md dark:bg-gray-900'
remove this dark modifier, reason there is not dark mode or light mode on website. It would be good so color remain consistent over the dark and light mode

2023-04-14 10:44 UTC, Chandraprakash-Darji requested changes

2023-04-14 10:44 UTC, Chandraprakash-Darji commented on src/components/PageComp/HomePage/Work.jsx
> +            <div key={company.id} className='m-4 h-20 w-48 rounded-md'>
add background color and `h-28 w-56 rounded-lg bg-base-200  border border-white/20` light border

2023-04-14 10:44 UTC, Chandraprakash-Darji commented on src/components/PageComp/HomePage/Work.jsx
> +        <div className='mx-auto mt-12 flex max-w-4xl flex-wrap items-center justify-center'>
remove max with , reson: section looks too shrinked

2023-04-14 11:09 UTC, Chandraprakash-Darji requested changes

2023-04-14 11:09 UTC, Chandraprakash-Darji commented on src/components/PageComp/HomePage/Work.jsx
> +      <div className='mx-auto max-w-7xl px-4 sm:px-6 lg:px-8'>
I just get that, add layout class here and no need for max-w and px

2023-04-14 11:09 UTC, Chandraprakash-Darji commented on src/components/PageComp/HomePage/Work.jsx
> +        <div className='mx-auto max-w-2xl'>
you can remove this div

2023-04-14 11:09 UTC, Chandraprakash-Darji commented on src/components/PageComp/HomePage/Work.jsx
> +        <div className='mx-auto mt-12 flex flex-wrap items-center justify-center'>
remove mt from here also. for consistent design along website

2023-04-14 15:45 UTC, Chandraprakash-Darji approved these changes
@harmanbatheja15 Great work man

2023-04-14 15:46 UTC, Chandraprakash-Darji commented
@harmanbatheja15 just update with screenshot so when we look back we get the changes

2023-04-14 15:57 UTC, harmanbatheja15 commented
Here is the new design for the work section:

<img width="2240" alt="Screenshot 2023-04-14 at 9 25 44 PM" src="https://user-images.githubusercontent.com/66913564/232094886-9c5f3094-4794-4371-8e79-bb89b0df710d.png">

2023-04-16 06:13 UTC, merged