Update greetings.yaml
WeMakeDevs/wemakedevs pull request #546
Opened 2023-04-09 15:28 UTC by shivam-sharma7

typo-fix: issue-message
update: pr-message

## Check List (Check all the boxes which are applicable) 

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

Add all the screenshots which support your changes

2023-04-09 15:31 UTC, shivam-sharma7 commented
review/ @AnuragThePathak

2023-04-11 16:33 UTC, AnuragThePathak commented on .github/workflows/greetings.yaml
> +          pr-message: Woah! Thanks to open your first Pull Request in our community, Congratulations 🎉 and thank you for your contribution! 🚀 The team will review it on <u>availability</u> 💫. In the
~~Thanks to open~~ Thanks for opening

2023-04-14 09:43 UTC, AnuragThePathak requested changes

2023-04-14 09:43 UTC, AnuragThePathak commented on .github/workflows/greetings.yaml
> +          pr-message: Woah! Thanks for opening your first Pull Request in our community, Congratulations 🎉 and thank you for your contribution! 🚀 The team will review it on <u>availability</u> 💫. In
Revert it to this is your first Pull Request ig. Thanking is repeated in the new message.

2023-04-14 15:06 UTC, AnuragThePathak requested changes
Update the Discord link to https://discord.gg/wemakedevs

2023-04-14 15:51 UTC, AnuragThePathak approved these changes

2023-04-14 15:53 UTC, merged