open source page header done
WeMakeDevs/wemakedevs pull request #557
Opened 2023-04-13 06:53 UTC by hrutik7

## Fixes Issue

This PR fixes the following issues:

closes #issue-number

## Changes proposed

Here comes all the changes proposed through this PR

## Check List (Check all the boxes which are applicable) 

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

Add all the screenshots which support your changes

2023-04-13 16:15 UTC, Chandraprakash-Darji commented
@hrutik7 I would recommend when ever you create PR, just share the supporting screenshot.

2023-04-14 00:48 UTC, hrutik7 commented
ok

2023-04-14 00:49 UTC, hrutik7 commented
![image](https://user-images.githubusercontent.com/62372737/231913341-61e5856c-5b95-4207-bae9-7194ba96eed5.png)

2023-04-14 11:05 UTC, Chandraprakash-Darji requested changes

2023-04-14 11:05 UTC, Chandraprakash-Darji commented on src/components/PageComp/OpenSourcePage/Header.jsx
> +import HeroImg from '@/assets/opensource/collab.svg';
Put assets in public folder, we are shifting to use public folder

2023-04-14 11:05 UTC, Chandraprakash-Darji commented on src/components/PageComp/OpenSourcePage/About.jsx
> +import AboutImage from 'assets/home/aboutus.png';
try to find some image about open source
![image](https://user-images.githubusercontent.com/93640141/232027914-f4a9190b-174f-48a4-899e-fd3e91dd4dea.png)

2023-04-14 11:41 UTC, hrutik7 commented on src/components/PageComp/OpenSourcePage/Header.jsx
> +import HeroImg from '@/assets/opensource/collab.svg';
ok understood

2023-04-14 12:54 UTC, hrutik7 commented on src/components/PageComp/OpenSourcePage/About.jsx
> +import AboutImage from 'assets/home/aboutus.png';
![image](https://user-images.githubusercontent.com/62372737/232049062-a26edfd3-3d2c-4a03-820b-e437f40048db.png)

2023-04-14 15:43 UTC, Chandraprakash-Darji requested changes

2023-04-14 15:44 UTC, Chandraprakash-Darji commented
Solve the conflict

2023-04-15 02:57 UTC, hrutik7 commented on src/components/PageComp/OpenSourcePage/About.jsx
> +const About = ({ background = 'static' }) => {
ok @Chandraprakash-Darji understood

2023-04-16 08:25 UTC, Chandraprakash-Darji requested changes

2023-04-16 08:25 UTC, Chandraprakash-Darji commented on src/assets/opensource/collab.svg
Remove this asset file

2023-04-16 08:25 UTC, Chandraprakash-Darji commented on src/components/PageComp/OpenSourcePage/Header.jsx
> +import HeroImg from '@/assets/opensource/collab.svg';
This import line is not required I guess

2023-04-16 08:25 UTC, Chandraprakash-Darji commented on src/components/PageComp/OpenSourcePage/Header.jsx
> +          <img src={`/assets/images/OpenSource/collab.svg`} className='w-full' />
Remove the curly bracket, because it will produce the prettier and eslint error.

2023-04-16 08:55 UTC, hrutik7 commented on src/components/PageComp/OpenSourcePage/Header.jsx
> +          <img src={`/assets/images/OpenSource/collab.svg`} className='w-full' />
ok

2023-04-18 16:34 UTC, Chandraprakash-Darji approved these changes

2023-04-18 16:34 UTC, merged