work section heading
WeMakeDevs/wemakedevs pull request #570
Opened 2023-04-20 05:02 UTC by sid-talesara

## Fixes Issue

This PR fixes the following issues:

closes #issue-number

## Changes proposed

Here comes all the changes proposed through this PR

## Check List (Check all the boxes which are applicable) 

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

Add all the screenshots which support your changes

### Section heading before changes:
![image](https://user-images.githubusercontent.com/95763376/233262739-af371641-110f-4741-bdaf-4e3f1a650be1.png)

### Changes Made: Changed the color of section headline
![image](https://user-images.githubusercontent.com/95763376/233262629-ce81ae5f-e26c-414a-aa5d-fda32cb29070.png)

2023-04-22 18:21 UTC, AnuragThePathak commented
You have erased the changes for Heading color change in some commit.

2023-04-22 19:31 UTC, sid-talesara commented
> You have erased...

Restored the heading color change.

2023-04-23 09:12 UTC, AnuragThePathak approved these changes

2023-04-23 09:16 UTC, AnuragThePathak commented
@Chandraprakash-Darji is the heading color change fine?

2023-04-24 12:27 UTC, Sandeep-RN approved these changes
LGTM

2023-04-25 00:10 UTC, Chandraprakash-Darji commented
@sid-talesara make color `text-content` becuse it should be  consistent all over the website

2023-04-25 00:11 UTC, Chandraprakash-Darji requested changes

2023-04-25 00:11 UTC, Chandraprakash-Darji commented on src/pages/PerticularhackathonPage.jsx
> +                description: 'DevRel Manager @Civo',
undo this change, make this PR for the color fix only and also there is PR for this change already

2023-05-05 04:18 UTC, Vivekgaddigi approved these changes

2023-05-06 16:22 UTC, AnuragThePathak commented
@Chandraprakash-Darji it seems the contributor is no longer active. Would you be able to update the PR? You may also create a new PR as per your convenience.

2023-05-18 12:15 UTC, closed without merging