Updating Copyright Name and Year in LICENSE
WeMakeDevs/wemakedevs pull request #574
Opened 2023-04-22 13:53 UTC by Sandeep-RN

## Changes proposed

Changing name from "Community Classroom" to "WeMakeDevs"
Changing year from 2022 to 2023

## Screenshots
![image](https://user-images.githubusercontent.com/42804812/233788908-9d880261-0b28-4c91-8e05-1fd521136a2d.png)

2023-04-22 16:13 UTC, siddhant-khisty requested changes

2023-04-22 16:13 UTC, siddhant-khisty commented on LICENSE
> +Copyright (c) 2023 WeMakeDevs
```suggestion
Copyright (c) 2022 WeMakeDevs
```

2023-04-22 16:14 UTC, siddhant-khisty commented on LICENSE
> +Copyright (c) 2023 WeMakeDevs
We rebranded to WeMakeDevs in 2022, so I believe the year should stay 2022 as well.

2023-04-22 17:29 UTC, Sandeep-RN commented on LICENSE
> +Copyright (c) 2023 WeMakeDevs
I thought the year should be the current year,
But after you mentioned this, 
I did some research just now and i found out that, 

If we had made any updates to the license since the initial publication, we could list a range of years (2022-2023) to cover all years that the license was in effect.

So I'm confused now😅.

@kaiwalyakoparkar could you please confirm what we are supposed to?
Either to include the initial year of the project or to include range of years?

2023-04-22 18:25 UTC, kaiwalyakoparkar commented on LICENSE
> +Copyright (c) 2023 WeMakeDevs
@Sandeep-RN both are admissible. For consistency keep it `2022`

2023-04-22 18:35 UTC, kaiwalyakoparkar approved these changes
lgtm

2023-04-23 01:57 UTC, Sandeep-RN commented
@siddhant-khisty Please review this PR as well,
Thanks 😊.

2023-04-23 01:57 UTC, siddhant-khisty approved these changes
Lgtm

2023-04-23 03:15 UTC, Sandeep-RN commented
@siddhant-khisty @kaiwalyakoparkar 
If everything is Fine,
Can we please merge it.
Thanks 😊

2023-04-23 09:18 UTC, merged