Added course in nav bar
WeMakeDevs/wemakedevs pull request #60
Opened 2022-10-21 19:12 UTC by Anuj-Kumar-AJ

## Fixes Issue
<img width="1280" alt="2022-10-22" src="https://user-images.githubusercontent.com/45460554/197271558-a50398b8-5313-489c-bd5f-a122d6d7c1ee.png">

closes #issue-number

## Changes proposed

Here comes all the changes proposed through this PR

## Check List (Check all the boxes which are applicable) 

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

2022-10-21 23:40 UTC, shivam-sharma7 requested changes
I think, Java + DSA would be better. review/ @kaiwalyakoparkar

2022-10-21 23:40 UTC, shivam-sharma7 commented on src/components/navbar/Navbar.js
> +                <Dropdown.Item href="https://www.youtube.com/watch?v=rZ41y93P2Qo&list=PL9gnSGHSqcnr_DxHsP7AW9ftq0AtAyYqJ">DSA + JAVA + Interview Preparation</Dropdown.Item>
```suggestion
                <Dropdown.Item href="https://www.youtube.com/watch?v=rZ41y93P2Qo&list=PL9gnSGHSqcnr_DxHsP7AW9ftq0AtAyYqJ">Java + DSA</Dropdown.Item> 
```

2022-10-22 05:00 UTC, AnuragThePathak commented
You need to update the fill the slots in the template properly.

2022-10-22 19:43 UTC, kaiwalyakoparkar commented
@Anuj-Kumar-AJ please complete the pr tempalte as suggested by Anurag above

2022-10-22 20:11 UTC, Anuj-Kumar-AJ commented
hi @kaiwalyakoparkar, i am sorry but i don't understand about the PR template suggestion is it the checks I have to mark on the change proposed section? If that's the case I have done that right now. Also please tell I have just used the suggestion of my previous code review in this PR only. does that mean the changes I have performed in this PR is the same as if I have created a new PR with all the changes?  I am new to GitHub please do tell me about it :)

2022-10-26 17:34 UTC, AnuragThePathak commented
@Anuj-Kumar-AJ kindly mention which issue your PR fixes.

2022-10-27 06:57 UTC, Anuj-Kumar-AJ commented
@AnuragThePathak , my PR resolves issue #59

2022-10-27 10:24 UTC, AnuragThePathak commented
@Anuj-Kumar-AJ for your ease, I have updated the description of PR to add the issue number. But the next time, make sure you do not it properly while creating a PR against an issue. It is applicable to any project.

Secondly, kindly provide screenshots of before and after so reviewers can easily figure out what changes your PR brings.

2022-10-27 13:25 UTC, Anuj-Kumar-AJ commented
Thanks for the feedback @AnuragThePathak. I will keep that in mind :)

2022-11-09 03:18 UTC, AnuragThePathak commented
You need to resolve conflicts to get it merged.

2022-11-23 07:09 UTC, closed without merging

2022-11-23 07:10 UTC, Anuj-Kumar-AJ commented
this feature done not support responsive rendering for small screen sites, like mobile or tab