Refactor carousel side arrows styling and spacing in content
WeMakeDevs/wemakedevs pull request #610
Opened 2023-05-16 20:45 UTC by nayan-dey

I refactored the styling and adjusted the spacing of the side arrows in the carousel component. The changes made improve the visual appearance and ensure a more consistent user experience.

## Fixes Issue

This PR fixes the following issues:

closes #607 

Previously, the side arrows in the carousel had a default color and spacing that didn't align with the overall design aesthetic of the content. Recognizing the importance of consistency and cohesiveness in user interfaces, this commit addresses these concerns and brings significant improvements to the component's appearance.

## Changes proposed

Here comes all the changes proposed through this PR

## Check List (Check all the boxes which are applicable) 

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested **changes.**

## Screenshots

Add all the screenshots which support your changes

### **carousal before changes**

![arrow1](https://github.com/WeMakeDevs/wemakedevs/assets/133354699/68079bd9-6644-4b42-bcc6-825c7a72fcc3)

### **made some changes on the color and spacing**

![arrow2](https://github.com/WeMakeDevs/wemakedevs/assets/133354699/1358bffe-39aa-4d8e-b3c2-6c9b41df575d)
![arrow3](https://github.com/WeMakeDevs/wemakedevs/assets/133354699/c7f1444c-73a6-4dcb-8023-85d3ab70bdf3)
![arrow4](https://github.com/WeMakeDevs/wemakedevs/assets/133354699/c34020ae-7758-4c07-8d7c-5603f7d73899)

2023-05-17 08:35 UTC, Chandraprakash-Darji requested changes

2023-05-17 08:35 UTC, Chandraprakash-Darji commented on package.json
> +    "react-icons": "^4.8.0",
Don't update deps

2023-05-17 08:39 UTC, nayan-dey commented on package.json
> +    "react-icons": "^4.8.0",
Can I undo this part or it would be okay for this time

2023-05-17 13:58 UTC, Chandraprakash-Darji commented on package.json
> +    "react-icons": "^4.8.0",
just undo it

2023-05-17 16:28 UTC, nayan-dey commented on package.json
> +    "react-icons": "^4.8.0",
Hey, I did what you said.

2023-05-18 12:22 UTC, Chandraprakash-Darji approved these changes

2023-05-18 12:22 UTC, Chandraprakash-Darji approved these changes

2023-05-18 12:30 UTC, merged