Update Stats.jsx
WeMakeDevs/wemakedevs pull request #627
Opened 2023-05-24 16:47 UTC by deveshgoyal1000

Changed numbers to:
$20,000+ prizes
30,000+ participants
30+ countries
200,000+ empowered

## Fixes Issue #626
## Check List (Check all the boxes which are applicable) 
- [X] The title of my pull request is a short description of the requested changes.

2023-05-24 17:09 UTC, Chandraprakash-Darji requested changes

2023-05-24 17:09 UTC, Chandraprakash-Darji commented on src/components/PageComp/EventsPage/Stats.jsx
> +
remove extra line

2023-05-24 17:09 UTC, Chandraprakash-Darji commented on src/components/PageComp/EventsPage/Stats.jsx
> +            number={30,000}
remove `,` from number

2023-05-24 17:09 UTC, Chandraprakash-Darji commented on src/components/PageComp/EventsPage/Stats.jsx
> +            icon={bsfilltrophyfill}
This icon is not imported

2023-05-24 17:09 UTC, Chandraprakash-Darji commented on src/components/PageComp/EventsPage/Stats.jsx
> +            icon={IoIosPeople}
This icon import is wrong

2023-05-26 10:53 UTC, AnuragThePathak commented
@deveshgoyal1000 are you still working on it?

2023-05-26 11:33 UTC, deveshgoyal1000 commented
> @deveshgoyal1000 are you still working on it?

nope can i close this

2023-05-26 11:34 UTC, deveshgoyal1000 commented
@AnuragThePathak 
nope can I close this

2023-05-26 13:04 UTC, AnuragThePathak commented
No problem, I can do it for you.

2023-05-26 13:04 UTC, closed without merging