feat: add testimonials in hackathons page
WeMakeDevs/wemakedevs pull request #643
Opened 2023-05-26 08:55 UTC by Lucif3r-in

## Fixes Issue

This PR fixes the following issues:

closes #637

## Changes proposed

Here comes all the changes proposed through this PR
Added testimonials section to hackathons page which can be reproduced by 

## Check List (Check all the boxes which are applicable) 

- [x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x] All new and existing tests passed.
- [ x] This PR does not contain plagiarized content.
- [ x] The title of my pull request is a short description of the requested changes.

2023-05-26 19:08 UTC, Chandraprakash-Darji requested changes

2023-05-26 19:08 UTC, Chandraprakash-Darji commented on src/content/Webinars/GopherWebinar.js
> -    "In this talk, the speakers will explain why Golang is their go-to programming language, why individuals should consider adopting it as well (with its ease of learning being the first reason), an
undo this, because it is not under this issue

2023-05-26 19:08 UTC, Chandraprakash-Darji commented on src/content/Hackathons/Testimonial.js
> +    description: `We are currently hosting our first-ever Hackathon. So far we have over 1600 developers showing off their skills using NAPPTIVE 😮. They are all creating kickass apps and sharing thei
Remove this one, because it will be added in partners testinomial

2023-05-26 19:08 UTC, Chandraprakash-Darji commented on src/components/PageComp/HackathonsPage/Testimonials.jsx
> +      <p className='text-content/80'>{designation}</p>
Move this component to  `src/components/Cards`

2023-05-27 02:03 UTC, Lucif3r-in commented on src/content/Webinars/GopherWebinar.js
> -    "In this talk, the speakers will explain why Golang is their go-to programming language, why individuals should consider adopting it as well (with its ease of learning being the first reason), an
@Chandraprakash-Darji I have added single inverted commas as they were causing build errors.

2023-05-27 02:17 UTC, Lucif3r-in commented
@Chandraprakash-Darji Please review and suggest any change if required.

2023-05-28 18:40 UTC, AnuragThePathak commented on src/content/Webinars/GopherWebinar.js
> -    "In this talk, the speakers will explain why Golang is their go-to programming language, why individuals should consider adopting it as well (with its ease of learning being the first reason), an
This won't error occur, you just need to pull the latest commits.

2023-05-29 01:50 UTC, Lucif3r-in commented on src/content/Webinars/GopherWebinar.js
> -    "In this talk, the speakers will explain why Golang is their go-to programming language, why individuals should consider adopting it as well (with its ease of learning being the first reason), an
@AnuragThePathak Yes sir I guess it is resolved now. I don't have any changes in the recent commit regarding it.

2023-05-29 05:00 UTC, Chandraprakash-Darji requested changes

2023-05-29 05:00 UTC, Chandraprakash-Darji commented on src/components/Cards/TestimonialCard.jsx
> +      <p className='text-content/80'>{designation}</p>
@AnuragThePathak does we need the designation of the testinomial?

2023-05-29 05:01 UTC, Chandraprakash-Darji commented on src/content/Webinars/GopherWebinar.js
> -    "In this talk, the speakers will explain why Golang is their go-to programming language, why individuals should consider adopting it as well (with its ease of learning being the first reason), an
Make it double quote to undo it to original state

2023-05-29 07:36 UTC, AnuragThePathak commented on src/components/Cards/TestimonialCard.jsx
> +      <p className='text-content/80'>{designation}</p>
It's optional imo, perhaps from can be replaced by designation.

2023-05-29 12:30 UTC, Lucif3r-in commented on src/components/Cards/TestimonialCard.jsx
> +      <p className='text-content/80'>{designation}</p>
@AnuragThePathak @Chandraprakash-Darji Which one should I keep?

2023-05-29 12:41 UTC, Lucif3r-in commented on src/content/Hackathons/Testimonial.js
> +import prathamesh from '@/assets/hackathon/hackathonpage/prathamesh.jpg';
Done!

2023-05-29 12:41 UTC, Lucif3r-in commented on src/content/Webinars/GopherWebinar.js
> -    "In this talk, the speakers will explain why Golang is their go-to programming language, why individuals should consider adopting it as well (with its ease of learning being the first reason), an
Done!

2023-05-29 14:34 UTC, Chandraprakash-Darji requested changes

2023-05-29 14:34 UTC, Chandraprakash-Darji commented on public/assets/images/hackathonpage/steve.jpg
Remove Steve image, as we are not using it

2023-05-29 14:34 UTC, Chandraprakash-Darji commented on src/content/Webinars/GopherWebinar.js
> -    "In this talk, the speakers will explain why Golang is their go-to programming language, why individuals should consider adopting it as well (with its ease of learning being the first reason), an
Still there is changes, recheck it

2023-05-29 14:36 UTC, Chandraprakash-Darji commented on src/components/Cards/TestimonialCard.jsx
> +      <p className='text-content/80'>{designation}</p>
Remove it.

2023-05-29 15:01 UTC, Lucif3r-in commented on src/content/Webinars/GopherWebinar.js
> -    "In this talk, the speakers will explain why Golang is their go-to programming language, why individuals should consider adopting it as well (with its ease of learning being the first reason), an
![Screenshot 2023-05-29 184647](https://github.com/WeMakeDevs/wemakedevs/assets/85403534/b7870df5-b387-43e6-8f5a-7a4465e5bbfb)
If I make double quotes I am getting this error.

2023-05-30 08:02 UTC, Chandraprakash-Darji requested changes

2023-05-30 08:02 UTC, Chandraprakash-Darji commented on src/content/Webinars/GopherWebinar.js
> -    "In this talk, the speakers will explain why Golang is their go-to programming language, why individuals should consider adopting it as well (with its ease of learning being the first reason), an
Pull the recent changes
```
git pull origin main
```

Then it will not cause the problem

2023-05-30 08:32 UTC, Lucif3r-in commented on src/content/Webinars/GopherWebinar.js
> -    "In this talk, the speakers will explain why Golang is their go-to programming language, why individuals should consider adopting it as well (with its ease of learning being the first reason), an
I have done that and still getting the error let me raise a new PR.

2023-05-30 10:29 UTC, Lucif3r-in commented
Check PR #645 for recent updates.

2023-05-30 11:54 UTC, closed without merging