Update Faq.jsx
WeMakeDevs/wemakedevs pull request #648
Opened 2023-06-03 14:25 UTC by 007AnupamSharma

## Fixes Issue

This PR fixes the following issues:  [Enhancement] of FAQ component #614

closes #issue-number

## Changes proposed
fixed it ... in small devices, either one of those 6 needs to open, and after clicking on another accordion the previous one needs to be closed .

Here comes all the changes proposed through this PR

## Check List (Check all the boxes which are applicable) 

- [ x] My code follows the code style of this project.
- [ x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x] All new and existing tests passed.
- [ x] This PR does not contain plagiarized content.
- [ x] The title of my pull request is a short description of the requested changes.

## Screenshots

Add all the screenshots which support your changes
![image](https://github.com/WeMakeDevs/wemakedevs/assets/91144139/91f60964-48e2-4b65-a087-9aa3a726cd0c)
both will open separately
![image](https://github.com/WeMakeDevs/wemakedevs/assets/91144139/52de494c-84bc-425c-b405-1d689ff3c7fd)
 at a time only one faq component will open

2023-06-04 08:11 UTC, AnuragThePathak commented
@007AnupamSharma fix the eslint errors.

2023-06-04 09:37 UTC, 007AnupamSharma commented
@AnuragThePathak please check man I have made new commit

2023-06-04 18:36 UTC, AnuragThePathak commented
@007AnupamSharma also fix the checklist thing. Take reference from previously merged PRs if needed.

2023-06-05 14:44 UTC, 007AnupamSharma commented
@AnuragThePathak look i'm fresher in open-source .. so i'm not understanding what are u trying to say  .. please can you help me out

2023-06-07 17:51 UTC, AnuragThePathak commented
@007AnupamSharma https://stackoverflow.com/questions/47344571/how-to-draw-checkbox-or-tick-mark-in-github-markdown-table

2023-06-08 16:51 UTC, Chandraprakash-Darji requested changes

2023-06-08 16:51 UTC, Chandraprakash-Darji commented on src/components/layout/Faq.jsx
> -          <Accordion data={faq.slice(0, 3)}></Accordion>
Make it one column by default, no two-column layout.

2023-06-08 16:51 UTC, Chandraprakash-Darji commented on src/components/layout/Faq.jsx
> +  const [windowWidth, setWindowWidth] = useState(window.innerWidth);
As we are removing two column layout so no need for the state and effect

2023-06-11 08:07 UTC, Chandraprakash-Darji requested changes

2023-06-11 08:07 UTC, Chandraprakash-Darji commented on src/components/layout/Faq.jsx
> -          <Accordion data={faq.slice(0, 3)}></Accordion>
Just loop over the faq and render the AccordionItem instead of Accordion, and remove the grid-cols-2 class

2023-06-11 09:59 UTC, 007AnupamSharma commented
Like I had made the changes whatever you said @Chandraprakash-Darji please check it, bro

2023-06-12 16:46 UTC, AnuragThePathak commented
@007AnupamSharma mark the conversations as resolved.

2023-06-12 16:53 UTC, 007AnupamSharma commented
@AnuragThePathak Done

2023-06-13 11:11 UTC, Chandraprakash-Darji commented
@007AnupamSharma I tried running locally, but it is not running?

2023-07-29 10:45 UTC, AnuragThePathak commented
@007AnupamSharma are you still interested in working?

2023-08-04 13:01 UTC, AnuragThePathak commented
Closing due to inactivity.

2023-08-04 13:01 UTC, closed without merging