Build the Readme file
WeMakeDevs/wemakedevs pull request #66
Opened 2022-10-24 11:57 UTC by iqrafirdose

Added title ,about community classroom ,hyperlinks ,socials and contributors

## Fixes Issue

This PR fixes the following issues:
Build the Readme file.

closes #issue-number

## Changes proposed

Here comes all the changes proposed through this PR

## Check List (Check all the boxes which are applicable) 

- [ ] My code follows the code style of this project.
- [x ] My change requires a change to the documentation.
- [x ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots 
Add all the screenshots which support your changes
![image](https://user-images.githubusercontent.com/114678694/197520120-960b613e-1052-4b89-b139-56a0084a4baa.png)

![image](https://user-images.githubusercontent.com/114678694/197520213-7b2f84a9-9ee8-477e-a49f-0459ca6b780c.png)

2022-11-17 17:57 UTC, siddhant-khisty requested changes
Requested for some changes. Also I noticed you are exclusively using HTML syntax. Please use the standard markdown syntax wherever you can. Use HTML only where you need to position or align something

2022-11-17 17:57 UTC, siddhant-khisty commented on README.md
> +![image](https://user-images.githubusercontent.com/114678694/197405872-70828c30-9cba-4cb7-a671-b5b1f0f8256d.png)
The logo can be centered and it looks low quality. I'll send a logo with higher quality soon

2022-11-17 17:57 UTC, siddhant-khisty commented on README.md
> +<h1 align=center>COMMUNITY CLASSROOM</h1>
Please use title case instead of all caps. Also, a logo can be added here as well. Will provide it soon.

2022-11-17 17:57 UTC, siddhant-khisty commented on README.md
> +<li>Community Classroom is a community that provides quality and free education for all.</li>
This section can be a paragraph instead of a list. A list seems to repetitive as it's starting with `Community Classroom` on every line

2022-11-17 17:57 UTC, siddhant-khisty commented on README.md
> +![Courses](https://user-images.githubusercontent.com/114678694/197411491-73f21a05-b556-460f-91e7-821dc525a828.jpg)
I really like this logo. However, ln desktop version it seems to take up a lot of space. Please remove it for the time being. We can add it in later

2022-11-17 17:57 UTC, siddhant-khisty commented on README.md
> +https://commclassroom.github.io/commclassroom//
The website link as been updated to `commclasssroom.org`.

Also instead of giving the website link, a message could be added such as `[Click here](www.commclassroom.org) to visit the Community classroom website`

2022-11-17 17:57 UTC, siddhant-khisty commented on README.md
> +Before contributing ,see <a href="https://github.com/commclassroom/commclassroom/blob/main/CONTRIBUTING.md">Contribution guide</a> for more information.
The comma is placed wrongly

2022-11-17 17:57 UTC, siddhant-khisty commented on README.md
> +<h1>Badges</h1>
The badges section can be moved up. After the title `Community Classroom` on line 2

2022-11-17 17:57 UTC, siddhant-khisty commented on README.md
> +<h1>Connect with us</h1>
This can be moved to before the contribution section. Please also add the discord and telegram links

2022-11-17 18:36 UTC, siddhant-khisty commented on README.md
> +![image](https://user-images.githubusercontent.com/114678694/197405872-70828c30-9cba-4cb7-a671-b5b1f0f8256d.png)
You can use this logo here
![Logo-removebg-preview](https://user-images.githubusercontent.com/73576223/202530107-bac0b82f-93cc-4fab-a8ed-4ca1ef06bd73.png)

2022-11-17 18:37 UTC, siddhant-khisty commented on README.md
> +<h1 align=center>COMMUNITY CLASSROOM</h1>
Icon for the above comment
![Icon](https://user-images.githubusercontent.com/73576223/202530262-be0eca52-558d-493e-ba83-d6ef3b69288e.png)

2022-11-19 14:55 UTC, iqrafirdose commented
Hello @siddhant-khisty, check this out. I hope you like it, and I did the changes that you have said.

2022-12-04 16:27 UTC, iqrafirdose commented
Hey, @siddhant-khisty , can you send a new logo? So, I can replace the community classroom with WeMakeDevs.

2022-12-05 03:41 UTC, Susmita-Dey commented
> Hey, @siddhant-khisty , can you send a new logo? So, I can replace the community classroom with WeMakeDevs.
![1](https://user-images.githubusercontent.com/79099734/205544472-0e5b04e7-69af-4d8c-8937-87f370656da6.png)

2022-12-06 07:26 UTC, samjn08 commented
This logo will work with both light theme and dark theme
![WMD logo](https://user-images.githubusercontent.com/81349382/205847446-a42e9edd-d6cc-4e1b-8c7d-5ba2bc901340.png)

2022-12-20 18:46 UTC, iqrafirdose commented
I created the read-me file of we make devs community, check this out. I hope you like it.

2022-12-21 15:50 UTC, kaiwalyakoparkar requested changes

2022-12-21 15:50 UTC, kaiwalyakoparkar commented on README.md
> +# Badges
No need for this particular heading. Kindly remove

2022-12-21 16:08 UTC, iqrafirdose commented on README.md
> +# Badges
> 

I removed @kaiwalyakoparkar .Thank you

2022-12-21 16:39 UTC, kaiwalyakoparkar requested changes

2022-12-21 16:39 UTC, kaiwalyakoparkar commented on README.md
> +<img src="https://user-images.githubusercontent.com/114678694/197411491-73f21a05-b556-460f-91e7-821dc525a828.jpg" width="360" height="270" >
Change aspect ratio of the image

2022-12-22 01:26 UTC, iqrafirdose commented on README.md
> +<img src="https://user-images.githubusercontent.com/114678694/197411491-73f21a05-b556-460f-91e7-821dc525a828.jpg" width="360" height="270" >
> Change aspect ratio of the image

can you please let me know, should I increase or decrease the aspect ratio

2022-12-25 06:00 UTC, Vishvsalvi commented
Is there anything I can do here?

2023-01-31 15:07 UTC, kaiwalyakoparkar commented on README.md
> +<img src="https://user-images.githubusercontent.com/114678694/197411491-73f21a05-b556-460f-91e7-821dc525a828.jpg" width="360" height="270" >
increase height

2023-02-04 08:36 UTC, AnuragThePathak commented
@iqrafirdose also resolve the conflicts

2023-02-06 09:40 UTC, siddhant-khisty requested changes

2023-02-06 09:40 UTC, siddhant-khisty commented on README.md
> +
Looks like there is a duplicate version of the readme created. Please remove the above duplicated section.

2023-02-06 17:15 UTC, iqrafirdose commented on README.md
> +<h1 id="logo"><a><img src="https://user-images.githubusercontent.com/114678694/208736801-03fbace3-5b00-42b9-8dfe-db18dcc13714.png" height="40" alt="logo"/> We Make Devs</a></h1>
Should I remove it?  and I will keep the  logo in the center 

> Perhaps we shouldn't have this heading for `WeMakeDevs` as there is a big logo just before it. @AnuragThePathak @kaiwalyakoparkar your thoughts on the matter?

Should I remove it? Then I will keep the logo in the center

2023-02-09 17:43 UTC, AnuragThePathak commented on README.md
> +<h1 id="logo"><a><img src="https://user-images.githubusercontent.com/114678694/208736801-03fbace3-5b00-42b9-8dfe-db18dcc13714.png" height="40" alt="logo"/> We Make Devs</a></h1>
The current changes by @iqrafirdose looks good to me.

2023-02-10 17:25 UTC, siddhant-khisty commented on README.md
> +<h1 id="logo"><a><img src="https://user-images.githubusercontent.com/114678694/208736801-03fbace3-5b00-42b9-8dfe-db18dcc13714.png" height="40" alt="logo"/> We Make Devs</a></h1>
@iqrafirdose the center logo sounds good. Please do that.

2023-02-11 06:13 UTC, AnuragThePathak commented
@iqrafirdose prefer resolving conversation.

2023-02-11 15:11 UTC, AnuragThePathak commented
@iqrafirdose you reacted to my message but didn't actually resolve the conversations. So I was wondering if you got what I meant?

2023-02-11 15:24 UTC, AnuragThePathak approved these changes

2023-02-11 15:25 UTC, iqrafirdose commented
> @iqrafirdose you reacted to my message but didn't actually resolve the conversations. So I was wondering if you got what I meant?

Actually, I resolved only recent conversation. Now, I resolve the conversations.

2023-02-11 15:26 UTC, merged