Couple of issues fixed
WeMakeDevs/wemakedevs pull request #695
Opened 2023-06-29 12:59 UTC by Subgor8126

## Fixes Issue

This PR fixes the following issues:

A typo was fixed on the Open Source courses section and the Google logo on the homepage was updated.

closes #687

2023-06-29 14:55 UTC, Chandraprakash-Darji approved these changes

2023-06-29 14:56 UTC, Chandraprakash-Darji commented
@AnuragThePathak one test failed check it once and also you added google logo but not not used it in work section

2023-06-29 15:18 UTC, Subgor8126 commented
Maybe there are no updates needed in the work section because the filename of the logo image is same as the previous one (google.svg).
I'm assuming that by work section you mean the Work.jsx file in src/components/PageComp/HomePage/

Please correct me if I'm wrong.

2023-06-29 15:41 UTC, Chandraprakash-Darji requested changes

2023-06-29 15:41 UTC, Chandraprakash-Darji commented on src/assets/home/company/google.svg
This should be svg, It is not rendering so Please re-check the file format

2023-06-29 15:47 UTC, AnuragThePathak commented
<img width="486" alt="Screen Shot 2023-06-29 at 9 16 23 P " src="https://github.com/WeMakeDevs/wemakedevs/assets/75429250/0303a09c-6c4f-494c-bc2e-66b5cc79ea5f">
@Subgor8126 you need to fix it.

2023-06-29 15:55 UTC, Chandraprakash-Darji requested changes

2023-06-29 15:55 UTC, Chandraprakash-Darji commented on src/assets/home/company/google.svg
You have added the black logo on black background

2023-06-29 15:55 UTC, Subgor8126 commented on src/assets/home/company/google.svg
Done

2023-06-29 16:17 UTC, Subgor8126 commented
please check if the logo appears to be black now

2023-07-02 10:24 UTC, AnuragThePathak commented
@Subgor8126 delete the latest commit, it has some problem so your workflow is failing (I assume it was just a simple merge, not resolving any conflicts).

2023-07-06 16:21 UTC, ItIsOHM commented
Hey @Subgor8126 @AnuragThePathak @Chandraprakash-Darji, I'd like to work on this issue as a beginner contributor. May I start working on it?

2023-07-06 18:17 UTC, AnuragThePathak commented
This is not an issue rather a PR. @ItIsOHM

2023-07-06 18:19 UTC, ItIsOHM commented
> This is not an issue rather a PR. @ItIsOHM

Oh right I'm sorry about that, will ask in the issue chat.

2023-07-07 05:43 UTC, Subgor8126 commented
@ItIsOHM can we work together on this PR? I am a beginner as well.

2023-07-07 08:45 UTC, ItIsOHM commented
> @ItIsOHM can we work together on this PR? I am a beginner as well.

Yea sure! Let me know here or anywhere else what's the status of this PR :D

2023-07-07 15:25 UTC, Subgor8126 commented
> > @ItIsOHM can we work together on this PR? I am a beginner as well.
> 
> Yea sure! Let me know here or anywhere else what's the status of this PR :D

It was probably a formatting issue. Can you please review the latest commit?

2023-07-07 15:31 UTC, Subgor8126 commented
@AnuragThePathak Please review the latest commit.

2023-07-07 19:43 UTC, AnuragThePathak commented
@Subgor8126 it'll be reviewed by @Chandraprakash-Darji as of now. I do not have idea about svgs. I'll assign to someone else if he doesn't review in 2-3 days. Just remind me.

2023-07-08 10:00 UTC, Subgor8126 commented
> @Subgor8126 it'll be reviewed by @Chandraprakash-Darji as of now. I do not have idea about svgs. I'll assign to someone else if he doesn't review in 2-3 days. Just remind me.

OK, will do

2023-07-08 10:05 UTC, Chandraprakash-Darji requested changes

2023-07-08 19:12 UTC, AnuragThePathak commented
@Subgor8126 your task is pretty simple now, Chandra has provided the svgs himself.

2023-07-09 07:06 UTC, Subgor8126 commented
@Chandraprakash-Darji please review the svg file now.

2023-07-13 05:51 UTC, AnuragThePathak approved these changes

2023-07-13 06:02 UTC, merged