Added colours to Footer icons in the website
WeMakeDevs/wemakedevs pull request #724
Opened 2023-07-23 12:58 UTC by SaptarshiSarkar12

## Fixes Issue

This PR fixes the following issues:

- closes #716 

## Changes proposed

Here comes all the changes proposed through this PR
- Added colours of the logo of socials to the icons in the WeMakeDevs website's footer.

## Check List (Check all the boxes which are applicable) 

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

Add all the screenshots which support your changes
![](https://user-images.githubusercontent.com/105960032/255393400-3b5d8927-510c-48bb-a2c1-3524623b2fde.png)
![](https://user-images.githubusercontent.com/105960032/255393376-f14199ab-87d7-4e8f-bdef-7ff92a6d3167.png)

2023-07-23 12:58 UTC, SaptarshiSarkar12 commented
I need some help on how to add hover effects @Chandraprakash-Darji @AnuragThePathak.

2023-07-23 12:59 UTC, Shiva953 commented
@SaptarshiSarkar12 for hover effect
try adding tailwind classes
```
className=`text-2xl transition-all duration-200 ease-in-out delay-200 hover:-translate-y-1`
```
[here](https://github.com/WeMakeDevs/wemakedevs/blob/e3985947b5d37a21f3671ecc49cf6fafb1a2b176/src/components/layout/Footer.jsx#L78C11-L89C17)

2023-07-23 13:06 UTC, SaptarshiSarkar12 commented
> @SaptarshiSarkar12 for hover effect try adding tailwind classes
> 
> ```
> className=`text-2xl transition-all duration-200 ease-in-out delay-200 hover:-translate-y-1`
> ```
> 
> [here](https://github.com/WeMakeDevs/wemakedevs/blob/e3985947b5d37a21f3671ecc49cf6fafb1a2b176/src/components/layout/Footer.jsx#L78C11-L89C17)

Yeah, hover effect works but colour disappears, don't know why. Could you please help @Shiva953 ?

2023-07-23 13:23 UTC, Shiva953 commented
> > @SaptarshiSarkar12 for hover effect try adding tailwind classes
> > ```
> > className=`text-2xl transition-all duration-200 ease-in-out delay-200 hover:-translate-y-1`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [here](https://github.com/WeMakeDevs/wemakedevs/blob/e3985947b5d37a21f3671ecc49cf6fafb1a2b176/src/components/layout/Footer.jsx#L78C11-L89C17)
> 
> Yeah, hover effect works but colour disappears, don't know why. Could you please help @Shiva953 ?

try replacing `{links.icon}` with `<span style={{ color: link.color }}>{link.icon}</span>`
and add a respective color property to each object in the `links` array
then edit `tailwind.config.js` and include the respective colours[this is the tricky bit though, colour themes are defined a bit differently here]

2023-07-23 13:25 UTC, SaptarshiSarkar12 commented
> > > @SaptarshiSarkar12 for hover effect try adding tailwind classes
> > > ```
> > > className=`text-2xl transition-all duration-200 ease-in-out delay-200 hover:-translate-y-1`
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > [here](https://github.com/WeMakeDevs/wemakedevs/blob/e3985947b5d37a21f3671ecc49cf6fafb1a2b176/src/components/layout/Footer.jsx#L78C11-L89C17)
> > 
> > 
> > Yeah, hover effect works but colour disappears, don't know why. Could you please help @Shiva953 ?
> 
> try replacing `{links.icon}` with `<span style={{ color: link.color }}>{link.icon}</span>` and add a respective color property to each object in the `links` array then edit `tailwind.config.js` and include the respective colours[this is the tricky bit though, colour themes are defined a bit differently here]

Hey @Shiva953, thank you for your ideas. I have tried tailwind css **text-[color]** property and it did work! But, I need a colour for the envelope icon, can you please suggest one?

2023-07-23 13:28 UTC, SaptarshiSarkar12 commented
@Shiva953 Here's the recording of the hover effect -

https://github.com/WeMakeDevs/wemakedevs/assets/105960032/a24e701b-6988-4a12-92c1-b32596e75e24

2023-07-23 13:28 UTC, Shiva953 commented
> > > > @SaptarshiSarkar12 for hover effect try adding tailwind classes
> > > > ```
> > > > className=`text-2xl transition-all duration-200 ease-in-out delay-200 hover:-translate-y-1`
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > [here](https://github.com/WeMakeDevs/wemakedevs/blob/e3985947b5d37a21f3671ecc49cf6fafb1a2b176/src/components/layout/Footer.jsx#L78C11-L89C17)
> > > 
> > > 
> > > Yeah, hover effect works but colour disappears, don't know why. Could you please help @Shiva953 ?
> > 
> > 
> > try replacing `{links.icon}` with `<span style={{ color: link.color }}>{link.icon}</span>` and add a respective color property to each object in the `links` array then edit `tailwind.config.js` and include the respective colours[this is the tricky bit though, colour themes are defined a bit differently here]
> 
> Hey @Shiva953, thank you for your ideas. I have tried tailwind css **text-[color]** property and it did work! But, I need a colour for the envelope icon, can you please suggest one?

try light yellow

2023-07-23 13:29 UTC, Shiva953 commented
> @Shiva953 Here's the recording of the hover effect -
> 
>  Screencast.from.2023-07-23.18-56-28.mp4

LGTM

2023-07-23 13:29 UTC, SaptarshiSarkar12 commented
Ok @Shiva953

2023-07-23 13:33 UTC, SaptarshiSarkar12 commented
@Shiva953 New Recording with the envelope color


https://github.com/WeMakeDevs/wemakedevs/assets/105960032/25f645a4-97aa-4450-a75f-a55daaf53112

2023-07-23 13:34 UTC, SaptarshiSarkar12 commented
@Shiva953 @Chandraprakash-Darji @AnuragThePathak Please review this PR.

2023-07-23 13:56 UTC, Shiva953 commented
> @Shiva953 @Chandraprakash-Darji @AnuragThePathak Please review this PR.

I think adding classnames as a property to the objects inside the links array makes it less reusable and chaotic. there must be a clean way of doing that with less and more re-usable code.

I was thinking of something similar to this : 
```
className={`text-2xl transition-all duration-200 ease-in-out delay-200 hover:-translate-y-1 hover:text-[${link.color}]`}
```

but it doesn't work
@Chandraprakash-Darji @AnuragThePathak thoughts?

2023-07-23 17:07 UTC, Chandraprakash-Darji commented
@Shiva953 Tailwind compile on runtime, so we can't use template literal string are not valid as a className 

> `text-[${color}]` will not work

> you should use `style={{color}}`

2023-07-23 17:14 UTC, Chandraprakash-Darji requested changes

2023-07-23 17:14 UTC, Chandraprakash-Darji commented on src/components/layout/Footer.jsx
> +      'text-2xl transition-all delay-200 duration-200 ease-in-out hover:-translate-y-1 hover:text-[#FF0000]',
ClassName should be like this
`className={clsxm( 'text-2xl transition-all delay-200 duration-200 ease-in-out hover:-translate-y-1', link.className)}`

And
In Object just ass the hover className

2023-07-23 17:14 UTC, Chandraprakash-Darji commented on src/components/layout/Footer.jsx
> +      'text-2xl transition-all delay-200 duration-200 ease-in-out hover:-translate-y-1 hover:text-[#46237a]',
Use this for discord color `#7289DA`

2023-07-23 18:03 UTC, SaptarshiSarkar12 commented on src/components/layout/Footer.jsx
> +      'text-2xl transition-all delay-200 duration-200 ease-in-out hover:-translate-y-1 hover:text-[#FF0000]',
Done @Chandraprakash-Darji ! Please re-review.

2023-07-23 18:03 UTC, SaptarshiSarkar12 commented on src/components/layout/Footer.jsx
> +      'text-2xl transition-all delay-200 duration-200 ease-in-out hover:-translate-y-1 hover:text-[#46237a]',
Done @Chandraprakash-Darji !

2023-07-25 16:20 UTC, SaptarshiSarkar12 commented
@Chandraprakash-Darji Please review this PR.

2023-07-29 07:47 UTC, SaptarshiSarkar12 commented
@Chandraprakash-Darji @AnuragThePathak Please review this PR.

2023-07-29 11:28 UTC, Chandraprakash-Darji approved these changes

2023-07-29 11:55 UTC, merged

2023-07-29 12:06 UTC, SaptarshiSarkar12 commented
Thank you @Chandraprakash-Darji and @AnuragThePathak for the merge :grinning: !