Rebuilt testimonial section for DSA page
WeMakeDevs/wemakedevs pull request #731
Opened 2023-08-02 04:52 UTC by Susmita-Dey

## Fixes Issue

This PR fixes the following issues:

closes #issue-number

## Changes proposed

- Updated the style of the testimonial section for the DSA course page
- Updated the data for the testimonial section

## Check List (Check all the boxes which are applicable) 

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

![image](https://github.com/WeMakeDevs/wemakedevs/assets/79099734/0f359841-64ab-4776-a31f-580dc37dc19e)

2023-08-03 05:15 UTC, Chandraprakash-Darji requested changes

2023-08-03 05:15 UTC, Chandraprakash-Darji commented on src/content/courses/dsa.js
> +    // tweetId: [
Remove the commented code

2023-08-03 05:15 UTC, Chandraprakash-Darji commented on src/content/courses/dsa.js
> +    data: [
rename to testimonial

2023-08-03 05:15 UTC, Chandraprakash-Darji commented on src/pages/SingleCoursePage.jsx
> +          <Component className={clsxm(as === 'section' && 'pt-20')}>
This component is copy pasted, Instead just send the data to the component

2023-08-03 08:29 UTC, Susmita-Dey commented on src/content/courses/dsa.js
> +    data: [
Done

2023-08-03 08:29 UTC, Susmita-Dey commented on src/pages/SingleCoursePage.jsx
> +          <Component className={clsxm(as === 'section' && 'pt-20')}>
Okay

2023-08-03 09:04 UTC, Susmita-Dey commented on src/content/courses/dsa.js
> +    // tweetId: [
done

2023-08-04 14:11 UTC, Ckbhatia approved these changes

2023-08-04 14:12 UTC, Ckbhatia commented
Everything looks good after recent changes!

2023-08-04 14:20 UTC, Ckbhatia commented on src/components/layout/Testimonials.jsx
> +          <TweetCarousael tweetId={tweetId} setTweetId={setTweetId} />
It would be much better if you just use composition here instead of passing props via the Testimonial component.

```
<Testimonials tweetCarousael={<TweetCarousael tweetId={tweetId} setTweetId={setTweetId} />}>
```

It will help with avoiding re-rendering. Tough, it's not a significant issue as per the current phase of this project.

2023-08-04 14:20 UTC, Ckbhatia commented on src/components/layout/Testimonials.jsx
> +                <AiFillRightCircle
See this for reference

2023-08-04 14:24 UTC, Ckbhatia commented on src/content/courses/dsa.js
> +        from: 'ARSALAN',
You should rename it with easy key names.
from = name
designation = twitterUsername

2023-08-04 14:25 UTC, Ckbhatia approved these changes

2023-08-05 04:07 UTC, Chandraprakash-Darji approved these changes

2023-08-05 04:08 UTC, Chandraprakash-Darji commented on src/components/layout/Testimonials.jsx
> +          <TweetCarousael tweetId={tweetId} setTweetId={setTweetId} />
This is bigger issue, not scope of this issue

2023-08-05 04:08 UTC, Chandraprakash-Darji commented on src/content/courses/dsa.js
> +        from: 'ARSALAN',
@Susmita-Dey You can make this change

2023-08-05 09:59 UTC, merged