Update README.md
WeMakeDevs/wemakedevs pull request #752
Opened 2023-08-23 17:31 UTC by nahidgaffar

Updated the old Twitter logo

## Fixes Issue

This PR fixes the following issues:

closes #issue-number

## Changes proposed

Here comes all the changes proposed through this PR

## Check List (Check all the boxes which are applicable) 

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

Add all the screenshots which support your changes

2023-08-26 04:26 UTC, AnuragThePathak commented
@siddhant-khisty did you add the previous icons?

2023-08-26 04:31 UTC, siddhant-khisty commented
@AnuragThePathak nope. Wasn't me. I think we can accept this change. It's just updating Twitter to X. This needs to be done for the footer of the website as well.

2023-08-26 04:33 UTC, siddhant-khisty requested changes

2023-08-26 04:33 UTC, siddhant-khisty commented on README.md
> +<a href="https://mobile.twitter.com/WeMakeDevs"><img src="https://github.com/nahidgaffar/privatehost/assets/135978438/eadd97ef-f3bb-4476-a9cd-dcf24649379a" height="60px"></img></a>
Please change the link to a publically accessible link. Currently, this link points to a private page. It might work in your repository because your repo has access to it, but it won't work in upstream.

Perhaps you can try to upload the image to a `user-images.githubusercontent.com` URL as the twitter logo was. If not, an alternative could be to upload the logo on imgur and then reference the image link here

2023-08-26 04:40 UTC, AnuragThePathak commented
@siddhant-khisty I don't think it's a good idea to use resources from PR creators server, because if he removes that at any point of time, we'll run into trouble. So better use something reliable used by many people.

2023-08-26 04:43 UTC, siddhant-khisty commented
@AnuragThePathak I agree with that. That's why I made the suggestion of Imgur or a different public URL

2023-08-26 06:01 UTC, nahidgaffar commented
@siddhant-khisty I have changed the link accordingly as you said. 
This time I used more reliable source and it's public as well.

2023-08-26 06:04 UTC, nahidgaffar commented
> @AnuragThePathak nope. Wasn't me. I think we can accept this change. It's just updating Twitter to X. This needs to be done for the footer of the website as well.

I can surely open a new PR for this aswell

2023-08-26 13:57 UTC, AnuragThePathak commented
@nahidgaffar do you mind sharing from where did you pick the logo?

2023-08-26 14:34 UTC, nahidgaffar commented
> @nahidgaffar do you mind sharing from where did you pick the logo?

I downloaded the logo from official Twitter [Brand Toolkit ](https://about.twitter.com/en/who-we-are/brand-toolkit)
Re edited it to match the style.
Uploaded it to public image [hosting](https://postimages.org/) site for image reliability.

2023-08-27 05:51 UTC, AnuragThePathak commented
Ok that's cool.

2023-08-27 05:52 UTC, AnuragThePathak approved these changes

2023-08-27 06:33 UTC, siddhant-khisty approved these changes
looks great. Thanks for the contribution 😄

2023-08-27 06:33 UTC, merged