Home Page Responsiveness Fixed
WeMakeDevs/wemakedevs pull request #99
Opened 2022-10-31 17:48 UTC by Lakshay-Pruthi

This PR fixes the following issues:
#96 #97 

## Changes proposed
The homepage has been made responsive now for all kind of media screens.
Also, the misalignment in the navbar contents and founder sections has been fixed.
Some small changes are also made which can be understood by viewing the screenshots attached below.

- [ x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x ] All new and existing tests passed.
- [ x ] This PR does not contain plagiarized content.
- [ x ] The title of my pull request is a short description of the requested changes.

Screenshots -->
1.
Before
![4](https://user-images.githubusercontent.com/91469717/199073216-258fb48c-0a59-40d3-84e9-649de2e4c6e5.png)

After
![4](https://user-images.githubusercontent.com/91469717/199073313-e23427e6-9ba0-49fc-9bd1-06e6c1d7f4a2.png)

2.
Before
![3](https://user-images.githubusercontent.com/91469717/199073458-38499350-d2ec-4ba2-af36-181e6cad5466.png)

After
![3](https://user-images.githubusercontent.com/91469717/199073534-34636caf-282d-46b2-9ad4-00c83ddbbd18.png)

3.Before
![5](https://user-images.githubusercontent.com/91469717/199073826-b192ba0f-02d3-4a85-91b1-a57c4ca8f2f7.png)

After
![5](https://user-images.githubusercontent.com/91469717/199073890-9151a9d6-4029-43a9-bffd-6d8e5d97a8b9.png)

4.
Before
![1](https://user-images.githubusercontent.com/91469717/199073968-e10fc5d6-d45f-4bac-b2dc-2b5aad088de9.png)

After
Founder image and text aligned
![1](https://user-images.githubusercontent.com/91469717/199074053-86af4975-3cc7-413c-9dc1-aa791427c3b2.png)

5.
Before
![2](https://user-images.githubusercontent.com/91469717/199074126-53e2680b-7437-4379-a94e-ce17f359ca1d.png)

After
YouTube button aligned in the center and with the nav items
![2](https://user-images.githubusercontent.com/91469717/199074185-308f21da-5e98-4591-9796-f2f47f98c5e1.png)

2022-10-31 17:54 UTC, Lakshay-Pruthi commented
Note: Some files may seem a lot of code has been deleted and added but this is not the case. As, Github also marks removing of spaces as changes (Code refactoring).
Some of the files where minor changes are done includes -->
1.About.css
2.Courses.css
3.Events.css
4.Mentorship.css
5.Podcast.css

2022-11-01 17:52 UTC, SuperAayush requested changes

2022-11-01 17:52 UTC, SuperAayush commented on src/styles/About.css
> -  }
Why is all the code of About.css removed and classes of blogs section is added here?

2022-11-09 03:16 UTC, AnuragThePathak commented
You need to resolve conflicts to get it merged.

2022-11-09 12:55 UTC, Lakshay-Pruthi commented
@AnuragThePathak Already resolved in previous commit. It is still showing conflicts because of the the last link added to the list items which is good to go. No problem there.

2022-11-09 18:24 UTC, Lakshay-Pruthi commented
@AnuragThePathak It is showing conflict because of the highlighted text
![image](https://user-images.githubusercontent.com/91469717/200910661-ca64a21b-8a2a-4883-b556-c5dc48d74e8b.png)
I can remove it if you want but it will create issues in Navbar responsiveness

2022-11-09 18:31 UTC, Lakshay-Pruthi commented
@AnuragThePathak Resolved!! Didn't knew about marking it as resolved.

2022-12-21 13:16 UTC, ManishBisht777 reviewed
I think its good to have one issue solved at a time , so it will be easy for others to review it

2022-12-22 06:21 UTC, Lakshay-Pruthi commented
> I think its good to have one issue solved at a time , so it will be easy for others to review it

Check this https://github.com/WeMakeDevs/wemakedevs/issues/96#issuecomment-1296941457

2022-12-22 13:08 UTC, closed without merging